import type { SettingsField } from '@hooksjam/pixi-lab-core';

export const SOFT_BODY_BLOB_SETTINGS_FIELDS: SettingsField[] = [
  {
    key: 'renderStyle',
    label: 'Style',
    section: 'Rendering',
    type: 'select',
    options: [
      { label: 'Basic', value: 'basic' },
      { label: 'Enhanced', value: 'enhanced' },
      { label: 'Ultra', value: 'ultra' },
    ],
    default: 'enhanced',
  },
  { key: 'blobSize', label: 'Blob Size', section: 'Physics', type: 'number', min: 18, max: 82, step: 1, default: 42, visibleQualities: ['raw'] },
  { key: 'nodeDensity', label: 'Node Density', section: 'Physics', type: 'number', min: 0.35, max: 2.5, step: 0.05, default: 1, visibleQualities: ['raw'] },
  { key: 'interactionRadius', label: 'Interaction Radius', section: 'Input Mode', type: 'number', min: 16, max: 280, step: 2, default: 72, visibleQualities: ['raw'], visibleModes: ['interact'] },
  { key: 'drawSmoothing', label: 'Draw Smoothing', section: 'Input Mode', type: 'number', min: 0, max: 1, step: 0.01, default: 0.45, visibleQualities: ['raw'], visibleModes: ['draw'] },
  { key: 'gravity', label: 'Gravity', section: 'Physics', type: 'number', min: 0, max: 2400, step: 25, default: 1250, visibleQualities: ['raw'] },
  { key: 'viscosity', label: 'Viscosity', section: 'Physics', type: 'number', min: 0, max: 1, step: 0.01, default: 0.64, visibleQualities: ['raw'] },
  { key: 'surfaceTension', label: 'Surface Tension', section: 'Physics', type: 'number', min: 0, max: 1, step: 0.01, default: 0.28, visibleQualities: ['raw'] },
  { key: 'plasticFlow', label: 'Plastic Flow', section: 'Physics', type: 'number', min: 0, max: 1, step: 0.01, default: 0.18, visibleQualities: ['raw'] },
  { key: 'boundaryElasticity', label: 'Boundary Elasticity', section: 'Physics', type: 'number', min: 0, max: 10, step: 0.01, default: 0.8, visibleQualities: ['raw'] },
  { key: 'membraneDamping', label: 'Membrane Damping', section: 'Physics', type: 'number', min: 0, max: 1, step: 0.01, default: 0.28, visibleQualities: ['raw'] },
  { key: 'areaPressure', label: 'Area Pressure', section: 'Physics', type: 'number', min: 0, max: 2, step: 0.01, default: 1, visibleQualities: ['raw'] },
  { key: 'skinSmoothing', label: 'Skin Smoothing', section: 'Rendering', type: 'number', min: 0, max: 0.85, step: 0.01, default: 0.46, visibleQualities: ['raw'], visibleRenderStyles: ['enhanced'] },
  { key: 'liquidFieldScale', label: 'Liquid Resolution', section: 'Rendering', type: 'number', min: 0.35, max: 1.5, step: 0.01, default: 0.82, visibleQualities: ['raw'], visibleRenderStyles: ['ultra'] },
  { key: 'liquidParticleRadius', label: 'Liquid Radius', section: 'Rendering', type: 'number', min: 0.55, max: 7.5, step: 0.01, default: 1.35, visibleQualities: ['raw'], visibleRenderStyles: ['ultra'] },
  { key: 'liquidFillDensity', label: 'Filler Density', section: 'Rendering', type: 'number', min: 0, max: 3, step: 0.01, default: 1.15, visibleQualities: ['raw'], visibleRenderStyles: ['basic', 'ultra'] },
  { key: 'liquidSplatDensity', label: 'Liquid Density', section: 'Rendering', type: 'number', min: 0.45, max: 2.5, step: 0.01, default: 1.2, visibleQualities: ['raw'], visibleRenderStyles: ['ultra'] },
  { key: 'liquidSurfaceThreshold', label: 'Surface Threshold', section: 'Rendering', type: 'number', min: 0.04, max: 0.42, step: 0.01, default: 0.17, visibleQualities: ['raw'], visibleRenderStyles: ['ultra'] },
  { key: 'liquidEdgeTightness', label: 'Edge Tightness', section: 'Rendering', type: 'number', min: 0, max: 1, step: 0.01, default: 0.72, visibleQualities: ['raw'], visibleRenderStyles: ['ultra'] },
  { key: 'liquidEdgeSoftness', label: 'Edge Softness', section: 'Rendering', type: 'number', min: 0, max: 1, step: 0.01, default: 0.54, visibleQualities: ['raw'], visibleRenderStyles: ['ultra'] },
  { key: 'liquidRefraction', label: 'Refraction', section: 'Rendering', type: 'number', min: 0, max: 1.5, step: 0.01, default: 0.64, visibleQualities: ['raw'], visibleRenderStyles: ['ultra'] },
  { key: 'liquidGloss', label: 'Specular Gloss', section: 'Rendering', type: 'number', min: 0, max: 1.5, step: 0.01, default: 0.72, visibleQualities: ['raw'], visibleRenderStyles: ['ultra'] },
  { key: 'liquidRimLighting', label: 'Rim Lighting', section: 'Rendering', type: 'number', min: 0, max: 2.5, step: 0.01, default: 0.82, visibleQualities: ['raw'], visibleRenderStyles: ['ultra'] },
  { key: 'liquidFoamStrength', label: 'Sparkle Foam', section: 'Rendering', type: 'number', min: 0, max: 3, step: 0.01, default: 0.38, visibleQualities: ['raw'], visibleRenderStyles: ['ultra'] },
  { key: 'liquidThermalStrength', label: 'Palette Flow', section: 'Rendering', type: 'number', min: 0, max: 1, step: 0.01, default: 0.48, visibleQualities: ['raw'], visibleRenderStyles: ['ultra'] },
  { key: 'liquidBloomStrength', label: 'Bloom', section: 'Rendering', type: 'number', min: 0, max: 3, step: 0.01, default: 0.3, visibleQualities: ['raw'], visibleRenderStyles: ['ultra'] },
  { key: 'liquidHeatShimmer', label: 'Heat Shimmer', section: 'Rendering', type: 'number', min: 0, max: 2, step: 0.01, default: 0.18, visibleQualities: ['raw'], visibleRenderStyles: ['ultra'] },
  { key: 'liquidDepthDiffusion', label: 'Depth Diffusion', section: 'Rendering', type: 'number', min: 0, max: 1, step: 0.01, default: 0.24, visibleQualities: ['raw'], visibleRenderStyles: ['ultra'] },
  { key: 'opacity', label: 'Opacity', section: 'Rendering', type: 'number', min: 0.2, max: 1, step: 0.01, default: 0.86, visibleQualities: ['raw'], visibleRenderStyles: ['ultra'] },
  { key: 'substeps', label: 'Substeps', section: 'Physics', type: 'number', min: 1, max: 5, step: 1, default: 2, visibleQualities: ['raw'] },
  { key: 'constraintPasses', label: 'Shape Passes', section: 'Physics', type: 'number', min: 2, max: 14, step: 1, default: 7, visibleQualities: ['raw'] },
  { key: 'squishiness', label: 'Squishiness', section: 'Physics', type: 'number', min: 0, max: 2, step: 0.01, default: 0.78, visibleQualities: ['raw'] },
];

export const SOFT_BODY_BLOB_DEFAULTS: Record<string, unknown> = {
  renderStyle: 'enhanced',
  blobSize: 42,
  nodeDensity: 1,
  interactionRadius: 72,
  drawSmoothing: 0.45,
  gravity: 1250,
  viscosity: 0.64,
  surfaceTension: 0.28,
  plasticFlow: 0.18,
  boundaryElasticity: 0.8,
  membraneDamping: 0.28,
  areaPressure: 1,
  skinSmoothing: 0.46,
  liquidFieldScale: 0.82,
  liquidParticleRadius: 1.35,
  liquidFillDensity: 1.15,
  liquidSplatDensity: 1.2,
  liquidSurfaceThreshold: 0.17,
  liquidEdgeTightness: 0.72,
  liquidEdgeSoftness: 0.54,
  liquidRefraction: 0.64,
  liquidGloss: 0.72,
  liquidRimLighting: 0.82,
  liquidFoamStrength: 0.38,
  liquidThermalStrength: 0.48,
  liquidBloomStrength: 0.3,
  liquidHeatShimmer: 0.18,
  liquidDepthDiffusion: 0.24,
  opacity: 0.86,
  substeps: 2,
  constraintPasses: 7,
  squishiness: 0.78,
};
