import type { SettingsField } from '@hooksjam/pixi-lab-core';

export const FLUID_TANK_SETTINGS_FIELDS: SettingsField[] = [
  {
    key: 'renderStyle',
    label: 'Style',
    section: 'Initialization',
    description: 'Chooses the raw WebGL dye initialization texture.',
    type: 'select',
    default: 'cloud',
    options: [
      { label: 'Cloud', value: 'cloud' },
      { label: 'Voronoi', value: 'voronoi' },
      { label: 'Random', value: 'random' },
      { label: 'Blank', value: 'blank' },
      { label: 'Image', value: 'image' },
    ],
  },
  { key: 'cellSize', label: 'Cell Size', section: 'Simulation', type: 'number', min: 0.25, max: 3.2, step: 0.05, default: 1.2 },
  { key: 'viscosity', label: 'Viscosity', section: 'Simulation', type: 'number', min: 0, max: 1, step: 0.01, default: 0.22 },
  { key: 'curl', label: 'Vorticity', section: 'Simulation', type: 'number', min: 0, max: 60, step: 0.5, default: 30 },
  { key: 'velocityPersistence', label: 'Velocity Dissipation', section: 'Simulation', type: 'number', min: 0, max: 1, step: 0.01, default: 0.2 },
  { key: 'dyePersistence', label: 'Density Dissipation', section: 'Simulation', type: 'number', min: 0, max: 2, step: 0.01, default: 1 },
  { key: 'pressureIterations', label: 'Pressure Solve', section: 'Simulation', type: 'number', min: 10, max: 36, step: 1, default: 24 },
  { key: 'ambient', label: 'Ambient Stir', section: 'Simulation', type: 'boolean', default: false },
  { key: 'shadingStrength', label: 'Surface Shading', section: 'Visual Style', type: 'number', min: 0, max: 1, step: 0.01, default: 1 },
  { key: 'bloomStrength', label: 'Bloom', section: 'Visual Style', type: 'number', min: 0, max: 1.8, step: 0.01, default: 0.8 },
  { key: 'bloomThreshold', label: 'Bloom Threshold', section: 'Visual Style', type: 'number', min: 0.08, max: 1.4, step: 0.01, default: 0.6 },
  { key: 'sunraysStrength', label: 'Sun Rays', section: 'Visual Style', type: 'number', min: 0, max: 1, step: 0.01, default: 1 },
  { key: 'fingerForce', label: 'Stir Force', section: 'Input Mode', type: 'number', min: 1, max: 80, step: 0.5, default: 18, visibleModes: ['stir', 'inject'] },
  { key: 'fingerRadius', label: 'Input Radius', section: 'Input Mode', type: 'number', min: 0.01, max: 0.09, step: 0.001, default: 0.05, visibleModes: ['stir', 'inject'] },
  { key: 'eddyAssist', label: 'Eddy Assist', section: 'Input Mode', type: 'number', min: 0, max: 0.35, step: 0.01, default: 0, visibleModes: ['stir'] },
  { key: 'injectAmount', label: 'Ink Amount', section: 'Input Mode', type: 'number', min: 0, max: 2, step: 0.01, default: 1, visibleModes: ['inject'] },
  { key: 'injectTurbulence', label: 'Ink Turbulence', section: 'Input Mode', type: 'number', min: 0, max: 1.5, step: 0.01, default: 0.45, visibleModes: ['inject'] },
  {
    key: 'injectPalette',
    label: 'Inject Color',
    section: 'Input Mode',
    type: 'select',
    default: 'style',
    visibleModes: ['inject'],
    options: [
      { label: 'Palette', value: 'style' },
      { label: 'Cyan', value: 'cyan' },
      { label: 'Magenta', value: 'magenta' },
      { label: 'Amber', value: 'amber' },
      { label: 'Green', value: 'green' },
      { label: 'Blue', value: 'blue' },
      { label: 'Red', value: 'red' },
      { label: 'White', value: 'white' },
      { label: 'Rainbow', value: 'rainbow' },
    ],
  },
  {
    key: 'initImageUrl',
    label: 'Image Source',
    section: 'Initialization',
    description: 'Optional direct image URL. If unset, Image style uses a random public image.',
    type: 'string',
    default: '',
    visibleRenderStyles: ['image'],
  },
];

export const FLUID_TANK_DEFAULTS: Record<string, unknown> = {
  timescale: 1,
  cellSize: 1.2,
  fingerForce: 18,
  fingerRadius: 0.05,
  viscosity: 0.22,
  curl: 30,
  eddyAssist: 0,
  velocityPersistence: 0.2,
  dyePersistence: 1,
  injectAmount: 1,
  injectTurbulence: 0.45,
  pressureIterations: 24,
  shadingStrength: 1,
  bloomStrength: 0.8,
  bloomThreshold: 0.6,
  sunraysStrength: 1,
  injectPalette: 'style',
  ambient: false,
  renderStyle: 'cloud',
  initImageUrl: '',
  style: 'bounded-cyan',
  screensaverMs: 60_000,
};
