import type { SettingsField } from '@hooksjam/pixi-lab-core';

export const FLUID_TANK_SETTINGS_FIELDS: SettingsField[] = [
  {
    key: 'renderStyle',
    label: 'Style',
    section: 'Initialization',
    description: 'Chooses the raw WebGL dye initialization texture.',
    type: 'select',
    default: 'cloud',
    options: [
      { label: 'Cloud', value: 'cloud' },
      { label: 'Voronoi', value: 'voronoi' },
      { label: 'Random', value: 'random' },
      { label: 'Blank', value: 'blank' },
      { label: 'Image', value: 'image' },
    ],
  },
  { key: 'timescale', label: 'Timescale', section: 'Simulation', type: 'number', min: 0, max: 2, step: 0.025, default: 1 },
  { key: 'cellSize', label: 'Cell Size', section: 'Simulation', type: 'number', min: 0.55, max: 3.2, step: 0.05, default: 1.2 },
  { key: 'viscosity', label: 'Viscosity', section: 'Simulation', type: 'number', min: 0, max: 1, step: 0.01, default: 0.22 },
  { key: 'curl', label: 'Swirl Memory', section: 'Simulation', type: 'number', min: 0, max: 24, step: 0.5, default: 6 },
  { key: 'dyePersistence', label: 'Dye Persistence', section: 'Simulation', type: 'number', min: 0.995, max: 1, step: 0.0001, default: 0.9996 },
  { key: 'pressureIterations', label: 'Pressure Solve', section: 'Simulation', type: 'number', min: 10, max: 36, step: 1, default: 24 },
  { key: 'ambient', label: 'Ambient Stir', section: 'Simulation', type: 'boolean', default: false },
  { key: 'fingerForce', label: 'Stir Force', section: 'Input Mode', type: 'number', min: 1, max: 32, step: 0.5, default: 8, visibleModes: ['stir', 'inject'] },
  { key: 'fingerRadius', label: 'Input Radius', section: 'Input Mode', type: 'number', min: 0.01, max: 0.08, step: 0.001, default: 0.026, visibleModes: ['stir', 'inject'] },
  { key: 'eddyAssist', label: 'Eddy Assist', section: 'Input Mode', type: 'number', min: 0, max: 0.35, step: 0.01, default: 0, visibleModes: ['stir'] },
  {
    key: 'injectPalette',
    label: 'Inject Color',
    section: 'Input Mode',
    type: 'select',
    default: 'style',
    visibleModes: ['inject'],
    options: [
      { label: 'Palette', value: 'style' },
      { label: 'Cyan', value: 'cyan' },
      { label: 'Magenta', value: 'magenta' },
      { label: 'Amber', value: 'amber' },
      { label: 'Green', value: 'green' },
      { label: 'Blue', value: 'blue' },
      { label: 'Red', value: 'red' },
      { label: 'White', value: 'white' },
      { label: 'Rainbow', value: 'rainbow' },
    ],
  },
  {
    key: 'initImageUrl',
    label: 'Image Source',
    section: 'Initialization',
    description: 'Optional direct image URL. If unset, Image style uses a random public image.',
    type: 'string',
    default: '',
    visibleRenderStyles: ['image'],
  },
];

export const FLUID_TANK_DEFAULTS: Record<string, unknown> = {
  timescale: 1,
  cellSize: 1.2,
  fingerForce: 8,
  fingerRadius: 0.026,
  viscosity: 0.22,
  curl: 6,
  eddyAssist: 0,
  dyePersistence: 0.9996,
  pressureIterations: 24,
  injectPalette: 'style',
  ambient: false,
  renderStyle: 'cloud',
  initImageUrl: '',
  style: 'bounded-cyan',
  screensaverMs: 60_000,
};
