import { createEngineConfigurations, type  AmbientDefinition } from '@hooksjam/pixi-lab-core';
import { DEFAULT_AMBIENT_BEHAVIOR } from '@hooksjam/pixi-lab-core';
import { SLEEP_AQUARIUM_DEFAULTS } from './sleep-aquarium.config.js';
import { SleepAquariumScene, sleepAquariumStyles } from './SleepAquariumScene.js';

export const sleepAquariumDefinition: AmbientDefinition = {
  id: 'sleep-aquarium',
  kind: 'ambient',
  renderModes: ['fullscreen', 'background', 'widget', 'previewTile'],
  name: 'Sleep Aquarium',
  short: 'A low-motion night reef with seeded fish and bubbles for passive dashboards.',
  long: 'Sleep Aquarium turns time and synthetic sleep signals into a dim, deterministic reef. Fish, bubbles, current strength, brightness, and budgets can be tuned live, and the ambient remains useful without media or home integrations.',
  tags: ['ambient', 'background', 'sleep', 'low-motion', 'dashboard', 'aquarium'],
  icon: '🐠',
  paletteHint: 'moonlit-reef',
  capabilities: {
    ambient: true,
    ambientLayer: true,
    tutorial: true,
    reset: true,
    debugOverlay: true,
    styleExport: true,
    lowMotion: true,
    sleepMode: true,
    engineConfigurations: createEngineConfigurations(['basic', 'enhanced']),
    settings: true,
  },
  dataBindings: [
    { source: 'time', optional: true, fallback: 'synthetic' },
    { source: 'synthetic', optional: false, fallback: 'idle' },
  ],
  behavior: {
    ...DEFAULT_AMBIENT_BEHAVIOR,
    maxBrightness: SLEEP_AQUARIUM_DEFAULTS.maxBrightness,
    maxParticleCount: SLEEP_AQUARIUM_DEFAULTS.fishCount + SLEEP_AQUARIUM_DEFAULTS.bubbleCount,
    maxUpdateHz: 24,
    allowForeground: false,
    allowBackground: true,
  },
  styles: sleepAquariumStyles,
  configDefaults: { ...SLEEP_AQUARIUM_DEFAULTS },
  settingsFields: [
    {
      key: 'fishCount',
      label: 'Fish Count',
      description: 'Seeded reef fish budget for fullscreen or dashboard use.',
      type: 'number',
      min: 24,
      max: 360,
      step: 12,
      default: SLEEP_AQUARIUM_DEFAULTS.fishCount,
    },
    {
      key: 'bubbleCount',
      label: 'Bubble Count',
      description: 'Soft bubble budget; reduced automatically in sleep and low-motion modes.',
      type: 'number',
      min: 12,
      max: 300,
      step: 12,
      default: SLEEP_AQUARIUM_DEFAULTS.bubbleCount,
    },
    {
      key: 'intensity',
      label: 'Intensity',
      description: 'Global brightness and reef visibility multiplier.',
      type: 'number',
      min: 0.08,
      max: 1,
      step: 0.04,
      default: SLEEP_AQUARIUM_DEFAULTS.intensity,
    },
    {
      key: 'maxBrightness',
      label: 'Max Brightness',
      description: 'Caps fish and bubble highlights for bedroom-safe dashboards.',
      type: 'number',
      min: 0.12,
      max: 0.7,
      step: 0.04,
      default: SLEEP_AQUARIUM_DEFAULTS.maxBrightness,
    },
    {
      key: 'currentStrength',
      label: 'Current Strength',
      description: 'Controls horizontal swim drift and bubble sway.',
      type: 'number',
      min: 0,
      max: 1,
      step: 0.05,
      default: SLEEP_AQUARIUM_DEFAULTS.currentStrength,
    },
    {
      key: 'sleepMode',
      label: 'Sleep Mode',
      description: 'Dims and thins the reef for night use.',
      type: 'boolean',
      default: SLEEP_AQUARIUM_DEFAULTS.sleepMode,
    },
    {
      key: 'lowMotion',
      label: 'Low Motion',
      description: 'Reduces current motion and visible particles while keeping the reef readable.',
      type: 'boolean',
      default: SLEEP_AQUARIUM_DEFAULTS.lowMotion,
    },
  ],
  factory: () => new SleepAquariumScene(false),
  previewFactory: () => new SleepAquariumScene(true),
  defaultSeed: 424242,
  tutorialPages: [
    {
      icon: '🌙',
      title: 'Bedroom-safe reef',
      body: 'Sleep Aquarium defaults to a dim passive mode with low particle budgets and gentle current motion.',
    },
    {
      icon: '🐠',
      title: 'Deterministic life',
      body: 'Fish lanes, bubble paths, colors, and motion are seeded so previews and fullscreen sessions stay reproducible.',
    },
    {
      icon: '🎚️',
      title: 'Live passive controls',
      body: 'Fish count, bubbles, intensity, brightness, current strength, sleep mode, and low motion all apply while the scene is running.',
    },
  ],
};
