import { createEngineConfigurations, type  AmbientDefinition } from '@hooksjam/pixi-lab-core';
import { DEFAULT_AMBIENT_BEHAVIOR } from '@hooksjam/pixi-lab-core';
import { HOME_WEATHER_GLASS_DEFAULTS } from './home-weather-glass.config.js';
import { HomeWeatherGlassScene, homeWeatherGlassStyles } from './HomeWeatherGlassScene.js';

export const homeWeatherGlassDefinition: AmbientDefinition = {
  id: 'home-weather-glass',
  kind: 'ambient',
  renderModes: ['fullscreen', 'background', 'widget', 'previewTile'],
  name: 'Home Weather Glass',
  short: 'A dashboard-safe weather pane with seeded rain glass driven by synthetic or injected weather data.',
  long: 'Home Weather Glass turns optional weather data into a quiet rainy window: humidity, precipitation, cloud cover, wind, and temperature shape droplets, brightness, and motion. It ships with synthetic fallback data so the demo remains useful without a live weather service.',
  tags: ['ambient', 'background', 'weather', 'dashboard', 'low-motion'],
  icon: '🌧️',
  paletteHint: 'rain-glass',
  capabilities: {
    ambient: true,
    ambientLayer: true,
    tutorial: true,
    reset: true,
    debugOverlay: true,
    styleExport: true,
    lowMotion: true,
    sleepMode: true,
    qualityModes: ['basic', 'enhanced'],
    engineConfigurations: createEngineConfigurations(['basic', 'enhanced']),
    settings: true,
  },
  dataBindings: [
    { source: 'weather', optional: true, fallback: 'synthetic' },
    { source: 'synthetic', optional: false, fallback: 'idle' },
  ],
  behavior: {
    ...DEFAULT_AMBIENT_BEHAVIOR,
    maxBrightness: HOME_WEATHER_GLASS_DEFAULTS.maxBrightness,
    maxParticleCount: HOME_WEATHER_GLASS_DEFAULTS.dropletCount,
    maxUpdateHz: 30,
    allowForeground: false,
    allowBackground: true,
  },
  styles: homeWeatherGlassStyles,
  configDefaults: { ...HOME_WEATHER_GLASS_DEFAULTS },
  settingsFields: [
    {
      key: 'dropletCount',
      label: 'Droplet Count',
      description: 'Seeded rain-glass particle budget for fullscreen/dashboard use.',
      type: 'number',
      min: 96,
      max: 1100,
      step: 32,
      default: HOME_WEATHER_GLASS_DEFAULTS.dropletCount,
    },
    {
      key: 'intensity',
      label: 'Intensity',
      description: 'Global brightness and weather motion multiplier.',
      type: 'number',
      min: 0.12,
      max: 1,
      step: 0.04,
      default: HOME_WEATHER_GLASS_DEFAULTS.intensity,
    },
    {
      key: 'maxBrightness',
      label: 'Max Brightness',
      description: 'Caps the glass highlights so dashboard UI remains readable.',
      type: 'number',
      min: 0.18,
      max: 0.75,
      step: 0.04,
      default: HOME_WEATHER_GLASS_DEFAULTS.maxBrightness,
    },
    {
      key: 'glassBlur',
      label: 'Glass Blur',
      description: 'Softens droplets into a rain-window look without requiring a live shader pass.',
      type: 'number',
      min: 0,
      max: 1,
      step: 0.05,
      default: HOME_WEATHER_GLASS_DEFAULTS.glassBlur,
    },
    {
      key: 'sleepMode',
      label: 'Sleep Mode',
      description: 'Dims and thins the weather pane for night dashboards.',
      type: 'boolean',
      default: HOME_WEATHER_GLASS_DEFAULTS.sleepMode,
    },
    {
      key: 'lowMotion',
      label: 'Low Motion',
      description: 'Reduces droplet motion and visible count while keeping the weather state readable.',
      type: 'boolean',
      default: HOME_WEATHER_GLASS_DEFAULTS.lowMotion,
    },
  ],
  factory: () => new HomeWeatherGlassScene(false),
  previewFactory: () => new HomeWeatherGlassScene(true),
  defaultSeed: 314159,
  tutorialPages: [
    {
      icon: '🌧️',
      title: 'Weather without a dependency',
      body: 'The ambient accepts real weather snapshots later, but the demo uses synthetic fallback data so the tile and fullscreen view always render.',
    },
    {
      icon: '🪟',
      title: 'Dashboard glass',
      body: 'Rain density, cloud cover, wind, humidity, and temperature shape a calm pane that stays behind UI instead of competing with it.',
    },
    {
      icon: '🌙',
      title: 'Passive-safe controls',
      body: 'Sleep mode, low motion, intensity, brightness, glass blur, and budget settings apply live while the scene runs.',
    },
  ],
};
