import type { AmbientDefinition } from '@hooksjam/pixi-lab-core';
import { DEFAULT_AMBIENT_BEHAVIOR } from '@hooksjam/pixi-lab-core';
import { MUSIC_DREAM_FIELD_DEFAULTS } from './music-dream-field.config.js';
import { MusicDreamFieldScene, musicDreamFieldStyles } from './MusicDreamFieldScene.js';

export const musicDreamFieldDefinition: AmbientDefinition = {
  id: 'music-dream-field',
  kind: 'ambient',
  renderModes: ['fullscreen', 'background', 'widget', 'previewTile'],
  name: 'Music Dream Field',
  short: 'A synthetic beat-reactive ambient with soft pulses for media dashboards.',
  long: 'Music Dream Field turns optional media snapshots into deterministic glowing orbs and aurora ribbons. It remains demoable without live media through synthetic beat fallback data, while live intensity, brightness, budget, low-motion, and sleep controls apply as the scene runs.',
  tags: ['ambient', 'background', 'music', 'media', 'low-motion', 'dashboard'],
  icon: '🎧',
  paletteHint: 'violet-dreamwave',
  capabilities: {
    ambient: true,
    ambientLayer: true,
    tutorial: true,
    reset: true,
    debugOverlay: true,
    styleExport: true,
    lowMotion: true,
    sleepMode: true,
    qualityModes: ['basic', 'enhanced'],
    settings: true,
  },
  dataBindings: [
    { source: 'media', optional: true, fallback: 'synthetic' },
    { source: 'time', optional: true, fallback: 'synthetic' },
    { source: 'synthetic', optional: false, fallback: 'idle' },
  ],
  behavior: {
    ...DEFAULT_AMBIENT_BEHAVIOR,
    maxBrightness: MUSIC_DREAM_FIELD_DEFAULTS.maxBrightness,
    maxParticleCount: MUSIC_DREAM_FIELD_DEFAULTS.orbCount + MUSIC_DREAM_FIELD_DEFAULTS.ribbonCount,
    maxUpdateHz: 30,
    allowForeground: false,
    allowBackground: true,
  },
  styles: musicDreamFieldStyles,
  configDefaults: { ...MUSIC_DREAM_FIELD_DEFAULTS },
  settingsFields: [
    {
      key: 'orbCount',
      label: 'Orb Count',
      description: 'Seeded pulse orb budget for fullscreen or dashboard use.',
      type: 'number',
      min: 24,
      max: 360,
      step: 12,
      default: MUSIC_DREAM_FIELD_DEFAULTS.orbCount,
    },
    {
      key: 'ribbonCount',
      label: 'Ribbon Count',
      description: 'Aurora ribbon budget; reduced automatically in low-motion and sleep modes.',
      type: 'number',
      min: 6,
      max: 120,
      step: 6,
      default: MUSIC_DREAM_FIELD_DEFAULTS.ribbonCount,
    },
    {
      key: 'intensity',
      label: 'Intensity',
      description: 'Global brightness multiplier for pulses and ribbons.',
      type: 'number',
      min: 0.08,
      max: 1,
      step: 0.04,
      default: MUSIC_DREAM_FIELD_DEFAULTS.intensity,
    },
    {
      key: 'maxBrightness',
      label: 'Max Brightness',
      description: 'Caps pulse highlights for passive room-safe displays.',
      type: 'number',
      min: 0.12,
      max: 0.72,
      step: 0.04,
      default: MUSIC_DREAM_FIELD_DEFAULTS.maxBrightness,
    },
    {
      key: 'beatSensitivity',
      label: 'Beat Sensitivity',
      description: 'Controls how strongly media or synthetic beat data affects pulse size and brightness.',
      type: 'number',
      min: 0,
      max: 1,
      step: 0.05,
      default: MUSIC_DREAM_FIELD_DEFAULTS.beatSensitivity,
    },
    {
      key: 'driftStrength',
      label: 'Drift Strength',
      description: 'Controls aurora drift and orb orbit amplitude.',
      type: 'number',
      min: 0,
      max: 1,
      step: 0.05,
      default: MUSIC_DREAM_FIELD_DEFAULTS.driftStrength,
    },
    {
      key: 'sleepMode',
      label: 'Sleep Mode',
      description: 'Dims and thins the field for night listening.',
      type: 'boolean',
      default: MUSIC_DREAM_FIELD_DEFAULTS.sleepMode,
    },
    {
      key: 'lowMotion',
      label: 'Low Motion',
      description: 'Reduces visible particles and movement while preserving the music mood.',
      type: 'boolean',
      default: MUSIC_DREAM_FIELD_DEFAULTS.lowMotion,
    },
  ],
  factory: () => new MusicDreamFieldScene(false),
  previewFactory: () => new MusicDreamFieldScene(true),
  defaultSeed: 525600,
  tutorialPages: [
    {
      icon: '🎧',
      title: 'Media-aware, demo-safe',
      body: 'Optional media snapshots can drive beat, tempo, and spectral flux, but synthetic fallback data keeps the ambient useful without integrations.',
    },
    {
      icon: '🌌',
      title: 'Deterministic dream field',
      body: 'Pulse orbs, aurora ribbons, colors, and movement are seeded so previews and fullscreen sessions remain reproducible.',
    },
    {
      icon: '🎚️',
      title: 'Live passive controls',
      body: 'Budgets, intensity, brightness, beat sensitivity, drift, sleep mode, and low motion all apply while the scene is running.',
    },
  ],
};
