import type { SettingsField } from '@hooksjam/pixi-lab-core';

export const ORBITAL_SHRAPNEL_SETTINGS_FIELDS: SettingsField[] = [
  { key: 'particleCount', label: 'Debris Count', type: 'number', min: 120, max: 1200, step: 40, default: 520 },
  { key: 'resolution', label: 'Resolution', type: 'number', min: 32, max: 512, step: 32, default: 64 },
  { key: 'gravity', label: 'Planet Gravity', type: 'number', min: 600, max: 3200, step: 50, default: 1550 },
  { key: 'planetRadius', label: 'Planet Radius', type: 'number', min: 22, max: 92, step: 2, default: 46 },
  { key: 'trailFade', label: 'Trail Persistence', type: 'number', min: 0.86, max: 0.995, step: 0.005, default: 0.955 },
  { key: 'debrisSize', label: 'Debris Size', type: 'number', min: 0.35, max: 2.4, step: 0.05, default: 0.58 },
  {
    key: 'trailGamma',
    label: 'Trail Contrast',
    description: 'Brightness curve for the orbital dust trail. Lower values reveal faint debris paths; higher values keep the field tighter.',
    type: 'number',
    min: 0.2,
    max: 0.9,
    step: 0.02,
    default: 0.36,
  },
  {
    key: 'rawParticleTextureSize',
    label: 'Raw Particle Texture',
    description: 'WebGL2-only particle state texture edge. Particle capacity is edge × edge; extreme tiers are clamped by the raw renderer plan.',
    type: 'select',
    default: '256',
    advanced: true,
    visibleEngineConfigurations: ['raw'],
    options: [
      { label: '256² = 65k · safe', value: '256' },
      { label: '512² = 262k · high', value: '512' },
      { label: '768² = 590k · advanced', value: '768' },
      { label: '1024² = 1.05M · extreme', value: '1024' },
    ],
  },
  {
    key: 'rawTrailTextureWidth',
    label: 'Raw Trail Texture',
    description: 'WebGL2-only trail field width. Height follows viewport aspect so trails stay crisp without distorting the field.',
    type: 'select',
    default: '320',
    advanced: true,
    visibleEngineConfigurations: ['raw'],
    options: [
      { label: '320 px · safe', value: '320' },
      { label: '512 px · high', value: '512' },
      { label: '768 px · advanced', value: '768' },
      { label: '1024 px · extreme', value: '1024' },
    ],
  },
  {
    key: 'rawMaxSpeed',
    label: 'Raw Max Speed',
    description: 'Velocity clamp used by the high-performance raw variant to keep million-particle orbital fields stable.',
    type: 'number',
    min: 0.25,
    max: 8,
    step: 0.05,
    default: 2.3,
    advanced: true,
    visibleEngineConfigurations: ['raw'],
  },
  {
    key: 'bloomStrength',
    label: 'Raw Bloom Strength',
    description: 'Additive glow multiplier for raw debris and trails. Keep this advanced because high bloom makes dense particle tiers visually intense.',
    type: 'number',
    min: 0,
    max: 2.5,
    step: 0.05,
    default: 1.25,
    advanced: true,
    visibleEngineConfigurations: ['raw'],
  },
  {
    key: 'streakStrength',
    label: 'Raw Streak Strength',
    description: 'Velocity-aligned debris streak multiplier for raw orbital fidelity tiers.',
    type: 'number',
    min: 0,
    max: 1.5,
    step: 0.05,
    default: 0.75,
    advanced: true,
    visibleEngineConfigurations: ['raw'],
  },
];

export const ORBITAL_SHRAPNEL_DEFAULTS: Record<string, unknown> = {
  particleCount: 520,
  resolution: 64,
  gravity: 1550,
  planetRadius: 46,
  drag: 0.002,
  trailFade: 0.955,
  rawParticleTextureSize: '256',
  rawTrailTextureWidth: '320',
  rawMaxSpeed: 2.3,
  debrisSize: 0.58,
  trailGamma: 0.36,
  bloomStrength: 1.25,
  streakStrength: 0.75,
  style: 'ice-ring',
  debug: false,
  screensaverMs: 60_000,
};
