import type { SettingsField } from '@hooksjam/pixi-lab-core';

export const ORBITAL_SHRAPNEL_SETTINGS_FIELDS: SettingsField[] = [
  { key: 'gravity', label: 'Planet Gravity', section: 'Planet', type: 'number', min: 600, max: 3200, step: 50, default: 1850 },
  { key: 'planetRadius', label: 'Planet Radius', section: 'Planet', type: 'number', min: 22, max: 92, step: 2, default: 46 },
  { key: 'trailFade', label: 'Trail Persistence', section: 'Rendering', type: 'number', min: 0, max: 0.995, step: 0.005, default: 0.972 },
  { key: 'debrisSize', label: 'Debris Size', section: 'Rendering', type: 'number', min: 0.05, max: 2.4, step: 0.05, default: 0.72 },
  { key: 'debrisOpacity', label: 'Debris Opacity', section: 'Rendering', description: 'Final visible debris opacity. Set to 0 to show only accumulated trails.', type: 'number', min: 0, max: 1, step: 0.01, default: 1 },
  { key: 'starField', label: 'Star Field', section: 'Rendering', description: 'Adds a static high-density background star layer.', type: 'boolean', default: true },
  { key: 'starFieldOpacity', label: 'Star Opacity', section: 'Rendering', description: 'Opacity of the static background star field.', type: 'number', min: 0, max: 1, step: 0.01, default: 0.42 },
  { key: 'addDebrisVolume', label: 'Add Volume', section: 'Input Mode', type: 'number', min: 0.005, max: 0.12, step: 0.005, default: 0.035, visibleModes: ['add'] },
  { key: 'addRadius', label: 'Add Radius', section: 'Input Mode', description: 'Radius of the area where newly emitted debris is scattered.', type: 'number', min: 2, max: 220, step: 1, default: 32, visibleModes: ['add'] },
  { key: 'addDebrisVelocity', label: 'Motion Inheritance', section: 'Input Mode', description: 'How strongly newly emitted debris inherits pointer/emitter movement.', type: 'number', min: 0, max: 1.4, step: 0.05, default: 0.35, visibleModes: ['add'] },
  { key: 'addJitter', label: 'Add Jitter', section: 'Input Mode', description: 'Random velocity variation applied to each newly emitted debris particle.', type: 'number', min: 0, max: 1.5, step: 0.025, default: 0.12, visibleModes: ['add'] },
  { key: 'interactionRadius', label: 'Interaction Radius', section: 'Input Mode', type: 'number', min: 16, max: 240, step: 2, default: 56, visibleModes: ['interact'] },
  { key: 'interactionStrength', label: 'Interaction Strength', section: 'Input Mode', type: 'number', min: 0.1, max: 12, step: 0.1, default: 3.2, visibleModes: ['interact'] },
  { key: 'wellRadius', label: 'Well Size', section: 'Input Mode', description: 'Radius of the gravity well input field.', type: 'number', min: 16, max: 280, step: 2, default: 72, visibleModes: ['well'] },
  { key: 'wellStrength', label: 'Well Pull', section: 'Input Mode', description: 'Attraction strength while the gravity well is held.', type: 'number', min: 0.1, max: 18, step: 0.1, default: 5.5, visibleModes: ['well'] },
  { key: 'secondaryBodyCount', label: 'Secondary Bodies', section: 'Secondary Bodies', type: 'number', min: 0, max: 8, step: 1, default: 3 },
  { key: 'secondaryBodyStrength', label: 'Body Pull', section: 'Secondary Bodies', type: 'number', min: 0, max: 1.5, step: 0.05, default: 0.35 },
  {
    key: 'secondaryBodyRadius',
    label: 'Max Body Orbit',
    section: 'Secondary Bodies',
    description: 'Upper placement limit for secondary bodies. Each body picks a distinct orbit inside this radius while staying outside the planet.',
    type: 'number',
    min: 0.2,
    max: 1.1,
    step: 0.025,
    default: 0.72,
  },
  {
    key: 'secondaryBodySpeed',
    label: 'Body Speed',
    section: 'Secondary Bodies',
    description: 'Multiplier for the stable circular orbit speed.',
    type: 'number',
    min: 0,
    max: 1.5,
    step: 0.025,
    default: 0.25,
  },
  {
    key: 'rawParticleTextureSize',
    label: 'Debris Density',
    section: 'Rendering',
    description: 'Particle state texture edge. Particle count equals edge x edge; higher values create denser orbital dust.',
    type: 'select',
    default: '192',
    advanced: true,
    visibleEngineConfigurations: ['raw'],
    options: [
      { label: '64² = 4k · preview', value: '64' },
      { label: '128² = 16k · light', value: '128' },
      { label: '192² = 37k · reference', value: '192' },
      { label: '256² = 65k · safe', value: '256' },
      { label: '512² = 262k · high', value: '512' },
      { label: '768² = 590k · advanced', value: '768' },
      { label: '1024² = 1.05M · extreme', value: '1024' },
    ],
  },
  {
    key: 'rawMaxSpeed',
    label: 'Velocity Limit',
    section: 'Rendering',
    description: 'Velocity clamp used to keep dense orbital fields stable.',
    type: 'number',
    min: 0.25,
    max: 8,
    step: 0.05,
    default: 2.3,
    advanced: true,
    visibleEngineConfigurations: ['raw'],
  },
  {
    key: 'bloomStrength',
    label: 'Glow Strength',
    section: 'Rendering',
    description: 'Additive glow multiplier for debris and trails.',
    type: 'number',
    min: 0,
    max: 2.5,
    step: 0.05,
    default: 1.25,
    advanced: true,
    visibleEngineConfigurations: ['raw'],
  },
  {
    key: 'streakStrength',
    label: 'Streak Length',
    section: 'Rendering',
    description: 'Velocity-aligned debris streak multiplier.',
    type: 'number',
    min: 0,
    max: 1.5,
    step: 0.05,
    default: 0.75,
    advanced: true,
    visibleEngineConfigurations: ['raw'],
  },
];

export const ORBITAL_SHRAPNEL_DEFAULTS: Record<string, unknown> = {
  gravity: 1850,
  planetRadius: 46,
  drag: 0.0016,
  trailFade: 0.972,
  rawParticleTextureSize: '192',
  rawMaxSpeed: 2.3,
  debrisSize: 0.72,
  debrisOpacity: 1,
  starField: true,
  starFieldOpacity: 0.42,
  addDebrisVolume: 0.035,
  addRadius: 32,
  addDebrisVelocity: 0.35,
  addJitter: 0.12,
  interactionRadius: 56,
  interactionStrength: 3.2,
  wellRadius: 72,
  wellStrength: 5.5,
  secondaryBodyCount: 3,
  secondaryBodyStrength: 0.35,
  secondaryBodyRadius: 0.72,
  secondaryBodySpeed: 0.25,
  bloomStrength: 1.25,
  streakStrength: 0.75,
  style: 'realistic',
  debug: false,
  screensaverMs: 60_000,
};
