import type { SettingsField } from '@hooksjam/pixi-lab-core';

export const SPLASH_MPM_SETTINGS_FIELDS: SettingsField[] = [
  {
    key: 'renderStyle',
    label: 'Style',
    section: 'Rendering',
    type: 'select',
    default: 'raw',
    options: [
      { label: 'Basic', value: 'basic' },
      { label: 'Enhanced', value: 'enhanced' },
      { label: 'Ultra', value: 'raw' },
    ],
  },
  { key: 'maxParticles', label: 'Particle Budget', section: 'Simulation', type: 'number', min: 2048, max: 131072, step: 1, numericScale: 'powerOfTwo', default: 32768 },
  { key: 'resolution', label: 'Resolution', section: 'Simulation', type: 'number', min: 32, max: 512, step: 1, numericScale: 'powerOfTwo', default: 128 },
  { key: 'stiffness', label: 'Pressure Stiffness', section: 'Simulation', type: 'number', min: 18, max: 180, step: 2, default: 86 },
  { key: 'restDensity', label: 'Rest Density', section: 'Simulation', type: 'number', min: 1.8, max: 8, step: 0.1, default: 3.2 },
  { key: 'viscosity', label: 'Grid Viscosity', section: 'Simulation', type: 'number', min: 0, max: 0.7, step: 0.01, default: 0.18 },
  { key: 'flipness', label: 'FLIP Blend', section: 'Simulation', type: 'number', min: 0, max: 1, step: 0.01, default: 0.88 },
  { key: 'gravity', label: 'Gravity', section: 'Simulation', type: 'number', min: 80, max: 1900, step: 20, default: 920 },
  { key: 'particleRadius', label: 'Droplet Size', section: 'Rendering', type: 'number', min: 1, max: 6, step: 0.1, default: 2.2 },
  { key: 'surfaceSmoothing', label: 'Surface Smoothing', section: 'Rendering', type: 'number', min: 0, max: 1, step: 0.01, default: 0.72 },
  { key: 'opacity', label: 'Opacity', section: 'Rendering', type: 'number', min: 0.18, max: 1, step: 0.01, default: 0.82 },
  { key: 'enhancedQuality', label: 'Metaball Detail', section: 'Enhanced Surface', type: 'number', min: 0.6, max: 1.4, step: 0.05, default: 1, visibleRenderStyles: ['enhanced'] },
  { key: 'enhancedSplatSize', label: 'Metaball Size', section: 'Enhanced Surface', type: 'number', min: 0.75, max: 1.7, step: 0.05, default: 1, visibleRenderStyles: ['enhanced'] },
  { key: 'enhancedDepth', label: 'Palette Depth', section: 'Enhanced Surface', type: 'number', min: 0, max: 1, step: 0.01, default: 0.62, visibleRenderStyles: ['enhanced'] },
  { key: 'enhancedEdge', label: 'Edge Definition', section: 'Enhanced Surface', type: 'number', min: 0, max: 1, step: 0.01, default: 0.58, visibleRenderStyles: ['enhanced'] },
  { key: 'inputRadius', label: 'Input Radius', section: 'Input Mode', type: 'number', min: 18, max: 160, step: 2, default: 62, visibleModes: ['splash', 'jet'] },
  { key: 'inputForce', label: 'Input Force', section: 'Input Mode', type: 'number', min: 2, max: 46, step: 1, default: 17, visibleModes: ['splash', 'jet'] },
  { key: 'emitRate', label: 'Jet Rate', section: 'Input Mode', type: 'number', min: 80, max: 1800, step: 20, default: 520, visibleModes: ['jet'] },
];

export const SPLASH_MPM_DEFAULTS: Record<string, unknown> = {
  renderStyle: 'raw',
  maxParticles: 32768,
  resolution: 128,
  stiffness: 86,
  restDensity: 3.2,
  viscosity: 0.18,
  flipness: 0.88,
  gravity: 920,
  particleRadius: 2.2,
  surfaceSmoothing: 0.72,
  opacity: 0.82,
  enhancedQuality: 1,
  enhancedSplatSize: 1,
  enhancedDepth: 0.62,
  enhancedEdge: 0.58,
  inputRadius: 62,
  inputForce: 17,
  emitRate: 520,
};
