import type { SettingsField } from '@hooksjam/pixi-lab-core';

export const SPLASH_MPM_SETTINGS_FIELDS: SettingsField[] = [
  {
    key: 'renderStyle',
    label: 'Style',
    section: 'Rendering',
    type: 'select',
    default: 'ultra',
    options: [
      { label: 'Basic', value: 'basic' },
      { label: 'Enhanced', value: 'enhanced' },
      { label: 'Ultra', value: 'ultra' },
    ],
  },
  { key: 'maxParticles', label: 'Particle Budget', section: 'Simulation', type: 'number', min: 2048, max: 131072, step: 1, numericScale: 'powerOfTwo', default: 32768 },
  { key: 'resolution', label: 'Resolution', section: 'Simulation', type: 'number', min: 32, max: 512, step: 1, numericScale: 'powerOfTwo', default: 128 },
  { key: 'stiffness', label: 'Pressure Stiffness', section: 'Simulation', type: 'number', min: 18, max: 180, step: 2, default: 86 },
  { key: 'restDensity', label: 'Rest Density', section: 'Simulation', type: 'number', min: 1.8, max: 8, step: 0.1, default: 3.2 },
  { key: 'particleSeparation', label: 'Particle Separation', section: 'Simulation', type: 'number', min: 0, max: 10, step: 0.01, default: 0.7 },
  { key: 'viscosity', label: 'Grid Viscosity', section: 'Simulation', type: 'number', min: 0, max: 0.7, step: 0.01, default: 0.18 },
  { key: 'flipness', label: 'FLIP Blend', section: 'Simulation', type: 'number', min: 0, max: 1, step: 0.01, default: 0.88 },
  { key: 'gravity', label: 'Gravity', section: 'Simulation', type: 'number', min: 80, max: 1900, step: 20, default: 920 },
  { key: 'particleRadius', label: 'Droplet Size', section: 'Simulation', type: 'number', min: 1, max: 64, step: 0.1, default: 4.2 },
  { key: 'surfaceSmoothing', label: 'Surface Smoothing', section: 'Rendering', type: 'number', min: 0, max: 1, step: 0.01, default: 0.72 },
  { key: 'opacity', label: 'Opacity', section: 'Rendering', type: 'number', min: 0.18, max: 1, step: 0.01, default: 0.82 },
  { key: 'enhancedQuality', label: 'Surface Detail', section: 'Enhanced Surface', type: 'number', min: 0.5, max: 2, step: 0.05, default: 1.25, visibleRenderStyles: ['enhanced', 'ultra'] },
  { key: 'enhancedSplatSize', label: 'Surface Kernel', section: 'Enhanced Surface', type: 'number', min: 0.65, max: 3.4, step: 0.05, default: 1.85, visibleRenderStyles: ['enhanced', 'ultra'] },
  { key: 'enhancedDepth', label: 'Palette Depth', section: 'Enhanced Surface', type: 'number', min: 0, max: 1, step: 0.01, default: 0.62, visibleRenderStyles: ['enhanced', 'ultra'] },
  { key: 'enhancedEdge', label: 'Edge Definition', section: 'Enhanced Surface', type: 'number', min: 0, max: 1, step: 0.01, default: 0.58, visibleRenderStyles: ['enhanced', 'ultra'] },
  { key: 'liquidFieldScale', label: 'Field Resolution', section: 'Enhanced Surface', type: 'number', min: 0.45, max: 1, step: 0.01, default: 0.78, visibleRenderStyles: ['enhanced', 'ultra'] },
  { key: 'liquidSurfaceThreshold', label: 'Surface Threshold', section: 'Enhanced Surface', type: 'number', min: 0.04, max: 0.72, step: 0.005, default: 0.1, visibleRenderStyles: ['enhanced', 'ultra'] },
  { key: 'liquidEdgeTightness', label: 'Edge Tightness', section: 'Enhanced Surface', type: 'number', min: 0.15, max: 1, step: 0.01, default: 0.82, visibleRenderStyles: ['enhanced', 'ultra'] },
  { key: 'liquidEdgeSoftness', label: 'Edge Softness', section: 'Enhanced Surface', type: 'number', min: 0, max: 2, step: 0.01, default: 0.46, visibleRenderStyles: ['enhanced', 'ultra'] },
  { key: 'liquidSplatDensity', label: 'Splat Density', section: 'Enhanced Surface', type: 'number', min: 0.45, max: 3.4, step: 0.01, default: 2.1, visibleRenderStyles: ['enhanced', 'ultra'] },
  { key: 'liquidParticleRadius', label: 'Surface Radius', section: 'Enhanced Surface', type: 'number', min: 0.7, max: 3.4, step: 0.01, default: 1.95, visibleRenderStyles: ['enhanced', 'ultra'] },
  { key: 'liquidRefraction', label: 'Refraction', section: 'Enhanced Surface', type: 'number', min: 0, max: 1, step: 0.01, default: 0.58, visibleRenderStyles: ['enhanced', 'ultra'] },
  { key: 'liquidGloss', label: 'Specular Gloss', section: 'Enhanced Surface', type: 'number', min: 0, max: 1, step: 0.01, default: 0.78, visibleRenderStyles: ['enhanced', 'ultra'] },
  { key: 'liquidFoamStrength', label: 'Foam Bloom', section: 'Enhanced Surface', type: 'number', min: 0, max: 6, step: 0.01, default: 2.4, visibleRenderStyles: ['ultra'] },
  { key: 'liquidBloomStrength', label: 'Soft Bloom', section: 'Enhanced Surface', type: 'number', min: 0, max: 3, step: 0.01, default: 0.34, visibleRenderStyles: ['ultra'] },
  { key: 'liquidHeatShimmer', label: 'Heat Shimmer', section: 'Enhanced Surface', type: 'number', min: 0, max: 2, step: 0.01, default: 0.16, visibleRenderStyles: ['ultra'] },
  { key: 'liquidDepthDiffusion', label: 'Depth Diffusion', section: 'Enhanced Surface', type: 'number', min: 0, max: 1, step: 0.01, default: 0.18, visibleRenderStyles: ['ultra'] },
  { key: 'inputRadius', label: 'Splash Radius', section: 'Input Mode', type: 'number', min: 18, max: 160, step: 2, default: 62, visibleModes: ['splash'] },
  { key: 'inputForce', label: 'Splash Force', section: 'Input Mode', type: 'number', min: 2, max: 46, step: 1, default: 17, visibleModes: ['splash'] },
  { key: 'emitRate', label: 'Pour Rate', section: 'Input Mode', type: 'number', min: 80, max: 1800, step: 20, default: 520, visibleModes: ['pour'] },
  { key: 'pourRadius', label: 'Pour Radius', section: 'Input Mode', type: 'number', min: 4, max: 120, step: 1, default: 34, visibleModes: ['pour'] },
  { key: 'buildRadius', label: 'Build Radius', section: 'Input Mode', type: 'number', min: 6, max: 48, step: 1, default: 18, visibleModes: ['build'] },
];

export const SPLASH_MPM_DEFAULTS: Record<string, unknown> = {
  renderStyle: 'ultra',
  maxParticles: 32768,
  resolution: 128,
  stiffness: 86,
  restDensity: 3.2,
  particleSeparation: 0.7,
  viscosity: 0.18,
  flipness: 0.88,
  gravity: 920,
  particleRadius: 4.2,
  surfaceSmoothing: 0.72,
  opacity: 0.82,
  enhancedQuality: 1.25,
  enhancedSplatSize: 1.85,
  enhancedDepth: 0.62,
  enhancedEdge: 0.58,
  liquidFieldScale: 0.78,
  liquidSurfaceThreshold: 0.1,
  liquidEdgeTightness: 0.82,
  liquidEdgeSoftness: 0.46,
  liquidSplatDensity: 2.1,
  liquidParticleRadius: 1.95,
  liquidRefraction: 0.58,
  liquidGloss: 0.78,
  liquidFoamStrength: 2.4,
  liquidBloomStrength: 0.34,
  liquidHeatShimmer: 0.16,
  liquidDepthDiffusion: 0.18,
  inputRadius: 62,
  inputForce: 17,
  emitRate: 520,
  pourRadius: 34,
  buildRadius: 18,
};
