/**
 * components/games/ballpit/ballpit.config.ts
 *
 * Ball Pit settings field definitions.
 */
import type { SettingsField } from '@hooksjam/pixi-lab-core';

export const BALLPIT_SETTINGS_FIELDS: SettingsField[] = [
  {
    key: 'maxParticles',
    label: 'Max Particles',
    section: 'Physics',
    type: 'number',
    min: 1_024,
    max: 262_144,
    step: 1,
    numericScale: 'powerOfTwo',
    default: 65_536,
  },
  {
    key: 'radius',
    label: 'Radius',
    section: 'Physics',
    type: 'number',
    min: 2,
    max: 64,
    step: 0.5,
    default: 12,
  },
  {
    key: 'radiusVariation',
    label: 'Radius Variation',
    section: 'Physics',
    type: 'number',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0.15,
  },
  {
    key: 'spawnRate',
    label: 'Spawn / sec',
    section: 'Input Mode',
    type: 'number',
    min: 50,
    max: 6_000,
    step: 50,
    default: 1200,
    visibleModes: ['stream'],
  },
  {
    key: 'interactionRadius',
    label: 'Interaction Radius',
    section: 'Input Mode',
    type: 'number',
    min: 16,
    max: 240,
    step: 2,
    default: 56,
    visibleModes: ['interact'],
  },
  {
    key: 'solverPasses',
    label: 'Solver Passes',
    section: 'Physics',
    type: 'number',
    min: 1,
    max: 8,
    step: 1,
    default: 3,
  },
  {
    key: 'substeps',
    label: 'Substeps',
    section: 'Physics',
    type: 'number',
    min: 1,
    max: 5,
    step: 1,
    default: 2,
  },
  {
    key: 'gravity',
    label: 'Gravity',
    section: 'Physics',
    type: 'number',
    min: 0,
    max: 3000,
    step: 25,
    default: 1300,
  },
  {
    key: 'burstCount',
    label: 'Explosion Force',
    section: 'Input Mode',
    type: 'number',
    min: 100,
    max: 10_000,
    step: 100,
    default: 5000,
    visibleModes: ['explosion'],
    advanced: true,
  },
  {
    key: 'wallBounce',
    label: 'Wall Bounce',
    section: 'Physics',
    type: 'boolean',
    default: false,
    advanced: true,
  },
  {
    key: 'friction',
    label: 'Friction',
    section: 'Physics',
    type: 'number',
    min: 0,
    max: 2,
    step: 0.05,
    default: 0.72,
    advanced: true,
  },
  {
    key: 'collisionSoftness',
    label: 'Collision Softness',
    section: 'Physics',
    type: 'number',
    min: 0.05,
    max: 1.5,
    step: 0.01,
    default: 0.82,
    advanced: true,
  },
  {
    key: 'maxPairPush',
    label: 'Push Cap',
    section: 'Physics',
    type: 'number',
    min: 0.02,
    max: 2,
    step: 0.01,
    default: 0.38,
    advanced: true,
  },
  {
    key: 'airDrag',
    label: 'Air Drag',
    section: 'Physics',
    type: 'number',
    min: 0.9,
    max: 1,
    step: 0.001,
    default: 0.998,
    advanced: true,
  },
  {
    key: 'solverDamping',
    label: 'Solver Damping',
    section: 'Physics',
    type: 'number',
    min: 0.9,
    max: 1,
    step: 0.001,
    default: 0.982,
    advanced: true,
  },
  {
    key: 'wallBounceAmount',
    label: 'Bounce Amount',
    section: 'Physics',
    type: 'number',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0.16,
    advanced: true,
  },
  {
    key: 'impactBounceThreshold',
    label: 'Impact Threshold',
    section: 'Physics',
    type: 'number',
    min: 0,
    max: 500,
    step: 10,
    default: 150,
    advanced: true,
  },
];

export const BALLPIT_DEFAULTS: Record<string, unknown> = {
  screensaverMs: 60_000,
  maxParticles: 65_536,
  radius: 12,
  radiusVariation: 0.15,
  spawnRate: 1200,
  interactionRadius: 56,
  solverPasses: 3,
  substeps: 2,
  gravity: 1300,
  burstCount: 5000,
  wallBounce: false,
  friction: 0.72,
  collisionSoftness: 0.82,
  maxPairPush: 0.38,
  airDrag: 0.998,
  solverDamping: 0.982,
  wallBounceAmount: 0.16,
  impactBounceThreshold: 150,
};
