import { createEngineConfigurations, DEFAULT_FOREGROUND_BEHAVIOR, type EffectDefinition } from '@hooksjam/pixi-lab-core';
import { RAIN_STREAKS_DEFAULTS } from './rain-streaks.config.js';
import { RainStreaksScene, rainStreaksStyleManifest } from './RainStreaksScene.js';

export const rainStreaksDefinition: EffectDefinition = {
  id: 'rain-streaks',
  kind: 'effect',
  renderModes: ['foregroundOverlay', 'fullscreen', 'previewTile'],
  name: 'Rain Streaks',
  short: 'A transparent foreground rain overlay with deterministic slanted streaks and weather fallback.',
  long: 'Rain Streaks is a foreground-safe weather overlay for dashboards and gallery demos. It renders deterministic seeded line particles, reads optional weather snapshots for rain, wind, and humidity, and falls back to synthetic data when live integrations are unavailable.',
  tags: ['effect', 'overlay', 'weather', 'rain', 'low-motion'],
  icon: '🌧️',
  paletteHint: 'storm-glass',
  capabilities: {
    reset: true,
    debugOverlay: true,
    styleExport: true,
    lowMotion: true,
    sleepMode: true,
    engineConfigurations: createEngineConfigurations(['basic', 'enhanced']),
    settings: true,
  },
  dataBindings: [
    { source: 'weather', optional: true, fallback: 'synthetic' },
    { source: 'synthetic', optional: false, fallback: 'idle' },
  ],
  behavior: {
    ...DEFAULT_FOREGROUND_BEHAVIOR,
    maxBrightness: RAIN_STREAKS_DEFAULTS.maxBrightness,
    maxParticleCount: RAIN_STREAKS_DEFAULTS.streakCount,
  },
  configDefaults: { ...RAIN_STREAKS_DEFAULTS },
  styleManifest: rainStreaksStyleManifest,
  settingsFields: [
    {
      key: 'streakCount',
      label: 'Streak Count',
      description: 'Seeded line-particle budget for the foreground overlay.',
      type: 'number',
      min: 48,
      max: 1400,
      step: 24,
      default: RAIN_STREAKS_DEFAULTS.streakCount,
    },
    {
      key: 'intensity',
      label: 'Intensity',
      description: 'Global rain brightness and motion multiplier.',
      type: 'number',
      min: 0.08,
      max: 1,
      step: 0.04,
      default: RAIN_STREAKS_DEFAULTS.intensity,
    },
    {
      key: 'maxBrightness',
      label: 'Max Brightness',
      description: 'Caps streak alpha so the overlay does not obscure UI.',
      type: 'number',
      min: 0.1,
      max: 0.72,
      step: 0.04,
      default: RAIN_STREAKS_DEFAULTS.maxBrightness,
    },
    {
      key: 'wind',
      label: 'Wind',
      description: 'Manual slant mixed with weather or synthetic fallback wind.',
      type: 'number',
      min: 0,
      max: 1,
      step: 0.04,
      default: RAIN_STREAKS_DEFAULTS.wind,
    },
    {
      key: 'speed',
      label: 'Speed',
      description: 'Controls rain fall speed while preserving deterministic paths.',
      type: 'number',
      min: 0,
      max: 1,
      step: 0.04,
      default: RAIN_STREAKS_DEFAULTS.speed,
    },
    {
      key: 'trailLength',
      label: 'Trail Length',
      description: 'Lengthens velocity arcs for heavier storm-glass streaks.',
      type: 'number',
      min: 0,
      max: 1,
      step: 0.04,
      default: RAIN_STREAKS_DEFAULTS.trailLength,
    },
    {
      key: 'sleepMode',
      label: 'Sleep Mode',
      description: 'Dims and thins rain for overnight passive displays.',
      type: 'boolean',
      default: RAIN_STREAKS_DEFAULTS.sleepMode,
    },
    {
      key: 'lowMotion',
      label: 'Low Motion',
      description: 'Reduces visible streaks and motion while keeping the rain legible.',
      type: 'boolean',
      default: RAIN_STREAKS_DEFAULTS.lowMotion,
    },
  ],
  factory: () => new RainStreaksScene(false),
  previewFactory: () => new RainStreaksScene(true),
  defaultSeed: 20260528,
  tutorialPages: [
    {
      icon: '🌧️',
      title: 'Foreground-safe rain',
      body: 'The effect renders transparent slanted line particles with capped brightness so dashboard UI remains readable.',
    },
    {
      icon: '🌦️',
      title: 'Weather optional',
      body: 'Rain, wind, and humidity can come from weather snapshots, but synthetic fallback data keeps the gallery demoable without integrations.',
    },
    {
      icon: '🌙',
      title: 'Passive controls',
      body: 'Streak budget, intensity, brightness, wind, speed, trail length, sleep mode, and low motion all apply while the scene runs.',
    },
  ],
};
