import type { SettingsField } from '@hooksjam/pixi-lab-core';
import { sparkSizeVariabilityField } from '../shared/spark-rendering.js';

export const FIREWORKS_SETTINGS_FIELDS: SettingsField[] = [
  { key: 'launchPower', label: 'Launch Power', section: 'Launch', type: 'number', min: 420, max: 1560, step: 20, default: 940 },
  { key: 'launchSpread', label: 'Origin Spread', section: 'Launch', type: 'number', min: 0, max: 0.62, step: 0.01, default: 0.18 },
  { key: 'shellFuse', label: 'Target Fuse Time', section: 'Launch', type: 'number', min: 0.55, max: 2.8, step: 0.05, default: 1.28 },
  { key: 'gravity', label: 'Gravity', section: 'Physics', type: 'number', min: 120, max: 760, step: 10, default: 360 },
  { key: 'airDrag', label: 'Air Drag', section: 'Physics', type: 'number', min: 0, max: 1.8, step: 0.05, default: 0.34 },
  { key: 'burstParticles', label: 'Burst Particle Budget', section: 'Explosion', description: 'Average GPU particle budget. Each burst rolls a size and derives its particle count from that size.', type: 'number', min: 16, max: 131072, step: 1, numericScale: 'powerOfTwo', default: 512 },
  { key: 'burstChaos', label: 'Burst Chaos', section: 'Explosion', type: 'number', min: 0, max: 1, step: 0.01, default: 0.82 },
  { key: 'explosionPower', label: 'Burst Power', section: 'Explosion', type: 'number', min: 90, max: 720, step: 10, default: 360 },
  { key: 'secondaryChance', label: 'Secondary Chance', section: 'Explosion', type: 'number', min: 0, max: 0.95, step: 0.01, default: 0.42 },
  { key: 'secondaryDepth', label: 'Secondary Depth', section: 'Explosion', type: 'number', min: 0, max: 3, step: 1, default: 2 },
  { key: 'secondaryScale', label: 'Secondary Size', section: 'Explosion', description: 'Scales child burst particle count and power per generation.', type: 'number', min: 0.18, max: 0.9, step: 0.01, default: 0.54 },
  { key: 'crackleIntensity', label: 'Crackle', section: 'Rendering', type: 'number', min: 0, max: 1.5, step: 0.05, default: 0.78 },
  { key: 'particleSize', label: 'Spark Size', section: 'Rendering', type: 'number', min: 0.45, max: 3.8, step: 0.05, default: 1.45 },
  sparkSizeVariabilityField(0.38),
  { key: 'trailFade', label: 'Trail Persistence', section: 'Rendering', type: 'number', min: 0.78, max: 0.995, step: 0.005, default: 0.932 },
  { key: 'bloomStrength', label: 'Glow Strength', section: 'Rendering', type: 'number', min: 0.4, max: 3.8, step: 0.05, default: 1.82 },
  { key: 'autoFinaleRate', label: 'Stream Rate', section: 'Input Mode', type: 'number', min: 0.2, max: 6, step: 0.1, default: 2.6, visibleModes: ['stream'] },
  {
    key: 'rawParticleTextureSize',
    label: 'GPU Particle Capacity',
    section: 'Rendering',
    description: 'Resident GPU particle pool size. Use Burst Particle Budget to influence emitted particles.',
    type: 'select',
    default: '384',
    advanced: true,
    options: [
      { label: '128² = 16k preview', value: '128' },
      { label: '256² = 65k light', value: '256' },
      { label: '384² = 147k reference', value: '384' },
      { label: '512² = 262k dense', value: '512' },
      { label: '768² = 590k stream', value: '768' },
      { label: '1024² = 1.05M extreme', value: '1024' },
    ],
  },
];

export const FIREWORKS_DEFAULTS: Record<string, unknown> = {
  launchPower: 940,
  launchSpread: 0.18,
  shellFuse: 1.28,
  gravity: 360,
  airDrag: 0.34,
  burstParticles: 512,
  burstChaos: 0.82,
  explosionPower: 360,
  secondaryChance: 0.42,
  secondaryDepth: 2,
  secondaryScale: 0.54,
  crackleIntensity: 0.78,
  particleSize: 1.45,
  sparkSizeVariability: 0.38,
  trailFade: 0.932,
  bloomStrength: 1.82,
  autoFinaleRate: 2.6,
  rawParticleTextureSize: '384',
  style: 'festival-night',
  debug: false,
  screensaverMs: 60_000,
};
