import type { SettingsField } from '@hooksjam/pixi-lab-core';

export const WATER_TANK_SETTINGS_FIELDS: SettingsField[] = [
  {
    key: 'renderStyle',
    label: 'Style',
    section: 'Rendering',
    type: 'select',
    options: [
      { label: 'Basic', value: 'basic' },
      { label: 'Enhanced', value: 'enhanced' },
      { label: 'Ultra', value: 'ultra' },
    ],
    default: 'enhanced',
  },
  { key: 'maxParticles', label: 'Max Particles', section: 'Physics', type: 'number', min: 512, max: 8192, step: 1, numericScale: 'powerOfTwo', default: 2048 },
  { key: 'particleRadius', label: 'Particle Radius', section: 'Physics', type: 'number', min: 1.6, max: 24, step: 0.1, default: 3.1 },
  { key: 'gravity', label: 'Gravity', section: 'Physics', type: 'number', min: 100, max: 2600, step: 25, default: 1120 },
  { key: 'viscosity', label: 'Viscosity Scale', section: 'Physics', type: 'number', min: 0, max: 12, step: 0.05, default: 1 },
  { key: 'viscositySigma', label: 'Linear Viscosity', section: 'Physics', type: 'number', min: 0, max: 3, step: 0.01, default: 0.9 },
  { key: 'viscosityBeta', label: 'Quadratic Viscosity', section: 'Physics', type: 'number', min: 0, max: 2, step: 0.01, default: 0.3 },
  { key: 'supportRadiusScale', label: 'Neighbor Radius', section: 'Physics', type: 'number', min: 1, max: 3.8, step: 0.05, default: 1.35 },
  { key: 'fluidGridResolution', label: 'Surface Resolution', section: 'Rendering', type: 'number', min: 128, max: 1024, step: 1, numericScale: 'powerOfTwo', default: 512 },
  { key: 'restDensity', label: 'Rest Density', section: 'Physics', type: 'number', min: 0.05, max: 4, step: 0.01, default: 0.72 },
  { key: 'stiffness', label: 'Stiffness', section: 'Physics', type: 'number', min: 0, max: 0.16, step: 0.001, default: 0.028 },
  { key: 'nearStiffness', label: 'Near Stiffness', section: 'Physics', type: 'number', min: 0, max: 5, step: 0.01, default: 1.15 },
  { key: 'neighborPairBudget', label: 'Neighbor Pair Budget', section: 'Physics', type: 'number', min: 8192, max: 262144, step: 1, numericScale: 'powerOfTwo', default: 65536 },
  { key: 'surfaceTension', label: 'Surface Settling', section: 'Physics', type: 'number', min: 0, max: 9000, step: 50, default: 900 },
  { key: 'collisionBounce', label: 'Collision Bounce', section: 'Physics', type: 'number', min: 0, max: 0.4, step: 0.01, default: 0.04 },
  { key: 'maxFluidSpeed', label: 'Velocity Limit', section: 'Physics', type: 'number', min: 300, max: 4200, step: 50, default: 2400 },
  { key: 'obstacleRamps', label: 'Obstacle Ramps', section: 'Tank Layout', type: 'number', min: 0, max: 8, step: 1, default: 4 },
  { key: 'obstaclePegs', label: 'Obstacle Pegs', section: 'Tank Layout', type: 'number', min: 0, max: 10, step: 1, default: 3 },
  { key: 'pourRate', label: 'Pour Rate', section: 'Input Mode', type: 'number', min: 500, max: 42000, step: 100, default: 9000, visibleModes: ['pour'] },
  { key: 'pourRadius', label: 'Pour Radius', section: 'Input Mode', type: 'number', min: 4, max: 120, step: 1, default: 34, visibleModes: ['pour'] },
  { key: 'buildRadius', label: 'Build Radius', section: 'Input Mode', type: 'number', min: 6, max: 48, step: 1, default: 18, visibleModes: ['build'] },
  { key: 'interactionRadius', label: 'Splash Radius', section: 'Input Mode', type: 'number', min: 20, max: 220, step: 2, default: 76, visibleModes: ['splash'] },
  { key: 'interactionStrength', label: 'Splash Strength', section: 'Input Mode', type: 'number', min: 2, max: 45, step: 1, default: 18, visibleModes: ['splash'] },
  { key: 'metaballBlend', label: 'Water Surface', section: 'Rendering', type: 'number', min: 0, max: 1, step: 0.01, default: 0.76 },
  { key: 'liquidFieldScale', label: 'Field Resolution', section: 'Enhanced Surface', type: 'number', min: 0.45, max: 1, step: 0.01, default: 0.78, visibleRenderStyles: ['enhanced', 'ultra'] },
  { key: 'liquidSurfaceThreshold', label: 'Surface Threshold', section: 'Enhanced Surface', type: 'number', min: 0.12, max: 0.72, step: 0.005, default: 0.18, visibleRenderStyles: ['enhanced', 'ultra'] },
  { key: 'liquidEdgeTightness', label: 'Edge Tightness', section: 'Enhanced Surface', type: 'number', min: 0.15, max: 1, step: 0.01, default: 0.82, visibleRenderStyles: ['enhanced', 'ultra'] },
  { key: 'liquidEdgeSoftness', label: 'Edge Softness', section: 'Enhanced Surface', type: 'number', min: 0, max: 2, step: 0.01, default: 0.46, visibleRenderStyles: ['enhanced', 'ultra'] },
  { key: 'liquidSplatDensity', label: 'Splat Density', section: 'Enhanced Surface', type: 'number', min: 0.45, max: 1.8, step: 0.01, default: 1.28, visibleRenderStyles: ['enhanced', 'ultra'] },
  { key: 'liquidParticleRadius', label: 'Surface Radius', section: 'Enhanced Surface', type: 'number', min: 0.7, max: 1.8, step: 0.01, default: 1.2, visibleRenderStyles: ['enhanced', 'ultra'] },
  { key: 'liquidRefraction', label: 'Refraction', section: 'Enhanced Surface', type: 'number', min: 0, max: 1, step: 0.01, default: 0.58, visibleRenderStyles: ['enhanced', 'ultra'] },
  { key: 'liquidGloss', label: 'Specular Gloss', section: 'Enhanced Surface', type: 'number', min: 0, max: 1, step: 0.01, default: 0.78, visibleRenderStyles: ['enhanced', 'ultra'] },
  { key: 'liquidFoamStrength', label: 'Foam Bloom', section: 'Enhanced Surface', type: 'number', min: 0, max: 6, step: 0.01, default: 2.4, visibleRenderStyles: ['ultra'] },
  { key: 'liquidBloomStrength', label: 'Soft Bloom', section: 'Enhanced Surface', type: 'number', min: 0, max: 3, step: 0.01, default: 0.34, visibleRenderStyles: ['ultra'] },
  { key: 'liquidHeatShimmer', label: 'Heat Shimmer', section: 'Enhanced Surface', type: 'number', min: 0, max: 2, step: 0.01, default: 0.16, visibleRenderStyles: ['ultra'] },
  { key: 'liquidDepthDiffusion', label: 'Depth Diffusion', section: 'Enhanced Surface', type: 'number', min: 0, max: 1, step: 0.01, default: 0.18, visibleRenderStyles: ['ultra'] },
  { key: 'opacity', label: 'Water Opacity', section: 'Rendering', type: 'number', min: 0.05, max: 1, step: 0.01, default: 0.74 },
  { key: 'substeps', label: 'Substeps', section: 'Physics', type: 'number', min: 1, max: 5, step: 1, default: 2 },
];

export const WATER_TANK_DEFAULTS: Record<string, unknown> = {
  renderStyle: 'enhanced',
  maxParticles: 2048,
  particleRadius: 3.1,
  gravity: 1120,
  viscosity: 1,
  viscositySigma: 0.9,
  viscosityBeta: 0.3,
  supportRadiusScale: 1.35,
  fluidGridResolution: 512,
  restDensity: 0.72,
  stiffness: 0.028,
  nearStiffness: 1.15,
  neighborPairBudget: 65536,
  surfaceTension: 900,
  collisionBounce: 0.04,
  maxFluidSpeed: 2400,
  obstacleRamps: 4,
  obstaclePegs: 3,
  pourRate: 9000,
  pourRadius: 34,
  buildRadius: 18,
  interactionRadius: 76,
  interactionStrength: 18,
  metaballBlend: 0.76,
  liquidFieldScale: 0.78,
  liquidSurfaceThreshold: 0.18,
  liquidEdgeTightness: 0.82,
  liquidEdgeSoftness: 0.46,
  liquidSplatDensity: 1.28,
  liquidParticleRadius: 1.2,
  liquidRefraction: 0.58,
  liquidGloss: 0.78,
  liquidFoamStrength: 2.4,
  liquidBloomStrength: 0.34,
  liquidHeatShimmer: 0.16,
  liquidDepthDiffusion: 0.18,
  opacity: 0.74,
  substeps: 2,
};
