import type { EffectDefinition } from '@hooksjam/pixi-lab-core';
import { SNOWFALL_DEFAULTS } from './snowfall.config.js';
import { SnowfallScene, snowfallStyleManifest } from './SnowfallScene.js';

export const snowfallDefinition: EffectDefinition = {
  id: 'snowfall',
  kind: 'effect',
  renderModes: ['foregroundOverlay', 'fullscreen', 'previewTile'],
  name: 'Snowfall',
  short: 'A passive foreground snow overlay with deterministic flakes and synthetic weather fallback.',
  long: 'Snowfall is a transparent foreground overlay for dashboards and galleries. It uses deterministic seeded flakes, optional weather snapshots, and synthetic fallback data so the effect remains demoable without a live weather integration.',
  tags: ['effect', 'overlay', 'weather', 'seasonal', 'low-motion'],
  icon: '❄️',
  paletteHint: 'moonlit-flurry',
  capabilities: {
    reset: true,
    debugOverlay: true,
    styleExport: true,
    lowMotion: true,
    sleepMode: true,
    qualityModes: ['basic', 'enhanced'],
    settings: true,
  },
  configDefaults: { ...SNOWFALL_DEFAULTS },
  styleManifest: snowfallStyleManifest,
  settingsFields: [
    {
      key: 'flakeCount',
      label: 'Flake Count',
      description: 'Seeded particle budget for the foreground overlay.',
      type: 'number',
      min: 48,
      max: 1200,
      step: 24,
      default: SNOWFALL_DEFAULTS.flakeCount,
    },
    {
      key: 'intensity',
      label: 'Intensity',
      description: 'Global snow brightness and motion multiplier.',
      type: 'number',
      min: 0.08,
      max: 1,
      step: 0.04,
      default: SNOWFALL_DEFAULTS.intensity,
    },
    {
      key: 'maxBrightness',
      label: 'Max Brightness',
      description: 'Caps flake alpha so the overlay does not obscure UI.',
      type: 'number',
      min: 0.12,
      max: 0.75,
      step: 0.04,
      default: SNOWFALL_DEFAULTS.maxBrightness,
    },
    {
      key: 'wind',
      label: 'Wind',
      description: 'Manual drift mixed with weather or synthetic fallback wind.',
      type: 'number',
      min: 0,
      max: 1,
      step: 0.04,
      default: SNOWFALL_DEFAULTS.wind,
    },
    {
      key: 'depthDrift',
      label: 'Depth Drift',
      description: 'Parallax sideways drift applied more strongly to near flakes.',
      type: 'number',
      min: 0,
      max: 1,
      step: 0.04,
      default: SNOWFALL_DEFAULTS.depthDrift,
    },
    {
      key: 'sleepMode',
      label: 'Sleep Mode',
      description: 'Dims and thins flakes for overnight passive displays.',
      type: 'boolean',
      default: SNOWFALL_DEFAULTS.sleepMode,
    },
    {
      key: 'lowMotion',
      label: 'Low Motion',
      description: 'Reduces drift and visible flakes while keeping snow readable.',
      type: 'boolean',
      default: SNOWFALL_DEFAULTS.lowMotion,
    },
  ],
  factory: () => new SnowfallScene(false),
  previewFactory: () => new SnowfallScene(true),
  defaultSeed: 20261224,
  tutorialPages: [
    {
      icon: '❄️',
      title: 'Foreground-safe snowfall',
      body: 'The effect is designed for a transparent foreground overlay and keeps brightness capped so UI stays readable.',
    },
    {
      icon: '🌦️',
      title: 'Weather optional',
      body: 'Weather snapshots can shape snow, temperature, and wind, but synthetic fallback data keeps the gallery demoable without integrations.',
    },
    {
      icon: '🌙',
      title: 'Passive controls',
      body: 'Flake budget, intensity, brightness, wind, depth drift, sleep mode, and low motion all apply while the scene runs.',
    },
  ],
};
