import type { SettingsField } from '@hooksjam/pixi-lab-core';

export const HARMONIC_SAND_SETTINGS_FIELDS: SettingsField[] = [
  { key: 'resolution', label: 'Resolution', type: 'number', min: 32, max: 512, step: 32, default: 128 },
  {
    key: 'baseFrequency',
    label: 'Base Frequency',
    type: 'number',
    min: 0.1,
    max: 10,
    step: 0.1,
    default: 2.4,
  },
  {
    key: 'rawParticleDensity',
    label: 'Raw Particle Density',
    description: 'Controls the density of GPU-rendered sand grains in the WebGL2 plate.',
    type: 'number',
    min: 0.35,
    max: 2.5,
    step: 0.05,
    default: 1.25,
    visibleEngineConfigurations: ['webgl2/high'],
  },
  {
    key: 'rawLineSharpness',
    label: 'Raw Line Sharpness',
    description: 'Narrows or softens the Chladni nodal bands in the raw shader.',
    type: 'number',
    min: 0.4,
    max: 3.5,
    step: 0.05,
    default: 1.8,
    visibleEngineConfigurations: ['webgl2/high'],
  },
  {
    key: 'rawGlow',
    label: 'Raw Glow',
    description: 'Boosts the bloom-like energy halo around resonant sand ridges.',
    type: 'number',
    min: 0.25,
    max: 3,
    step: 0.05,
    default: 1.35,
    visibleEngineConfigurations: ['webgl2/high'],
  },
  {
    key: 'rawWaveMix',
    label: 'Raw Wave Mix',
    description: 'Blends between orthogonal and radial harmonic wave families.',
    type: 'number',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0.42,
    visibleEngineConfigurations: ['webgl2/high'],
  },
];

export const HARMONIC_SAND_DEFAULTS: Record<string, unknown> = {
  resolution: 128,
  baseFrequency: 2.4,
  rawParticleDensity: 1.25,
  rawLineSharpness: 1.8,
  rawGlow: 1.35,
  rawWaveMix: 0.42,
  emitterCount: 0,
  style: 'chladni-gold',
  debug: false,
  screensaverMs: 60_000,
};
