import type { SettingsField } from '@hooksjam/pixi-lab-core';

export const HARMONIC_SAND_SETTINGS_FIELDS: SettingsField[] = [
  { key: 'resolution', label: 'Resolution', type: 'number', min: 32, max: 1024, step: 32, default: 128 },
  {
    key: 'baseFrequency',
    label: 'Base Frequency',
    type: 'number',
    min: 0.1,
    max: 10,
    step: 0.1,
    default: 2.4,
  },
  {
    key: 'wavePeriod',
    label: 'Wave Period',
    description: 'Controls wave phase speed: shorter is faster, longer is slower.',
    type: 'number',
    min: 0.2,
    max: 6,
    step: 0.1,
    default: 1,
  },
  {
    key: 'rawParticleCount',
    label: 'Raw Particle Count',
    description: 'Controls the apparent GPU sand budget in the WebGL2 plate.',
    type: 'number',
    min: 25000,
    max: 2000000,
    step: 25000,
    default: 180000,
    visibleEngineConfigurations: ['webgl2/high'],
  },
  {
    key: 'rawParticleDensity',
    label: 'Raw Particle Density',
    description: 'Fine-tunes how tightly GPU sand grains pack around resonance lines.',
    type: 'number',
    min: 0.35,
    max: 8,
    step: 0.05,
    default: 1.25,
    visibleEngineConfigurations: ['webgl2/high'],
  },
  {
    key: 'rawEmitterLimit',
    label: 'Raw Source Limit',
    description: 'Caps how many placed resonance sources the WebGL2 plate can hold.',
    type: 'number',
    min: 1,
    max: 16,
    step: 1,
    default: 10,
    visibleEngineConfigurations: ['webgl2/high'],
  },
  {
    key: 'rawLineSharpness',
    label: 'Raw Line Sharpness',
    description: 'Narrows or softens the Chladni nodal bands in the raw shader.',
    type: 'number',
    min: 0.4,
    max: 3.5,
    step: 0.05,
    default: 1.8,
    visibleEngineConfigurations: ['webgl2/high'],
  },
  {
    key: 'rawGlow',
    label: 'Raw Glow',
    description: 'Boosts the bloom-like energy halo around resonant sand ridges.',
    type: 'number',
    min: 0.25,
    max: 3,
    step: 0.05,
    default: 1.35,
    visibleEngineConfigurations: ['webgl2/high'],
  },
];

export const HARMONIC_SAND_DEFAULTS: Record<string, unknown> = {
  resolution: 128,
  baseFrequency: 2.4,
  wavePeriod: 1,
  rawParticleCount: 180000,
  rawParticleDensity: 1.25,
  rawEmitterLimit: 10,
  rawLineSharpness: 1.8,
  rawGlow: 1.35,
  emitterCount: 0,
  style: 'chladni-gold',
  debug: false,
  screensaverMs: 60_000,
};
