import type { SettingsField } from '@hooksjam/pixi-lab-core';

export const HARMONIC_SAND_SETTINGS_FIELDS: SettingsField[] = [
  {
    key: 'renderStyle',
    label: 'Style',
    section: 'Rendering',
    description: 'Chooses the raw WebGL render path.',
    type: 'select',
    options: [
      { label: 'Basic', value: 'basic' },
      { label: 'Enhanced', value: 'enhanced' },
      { label: 'Ultra', value: 'ultra' },
    ],
    default: 'ultra',
  },
  { key: 'resolution', label: 'Resolution', section: 'Simulation', type: 'number', min: 32, max: 2048, step: 1, numericScale: 'powerOfTwo', default: 128 },
  {
    key: 'baseFrequency',
    label: 'Base Frequency',
    section: 'Simulation',
    type: 'number',
    min: 0.1,
    max: 10,
    step: 0.1,
    default: 2.4,
  },
  {
    key: 'wavePeriod',
    label: 'Wave Period',
    section: 'Simulation',
    description: 'Controls wave phase speed: shorter is faster, longer is slower.',
    type: 'number',
    min: 1.0,
    max: 6,
    step: 0.1,
    default: 1,
  },
  {
    key: 'rawParticleCount',
    label: 'Particle Count',
    section: 'Rendering',
    description: 'Controls the apparent GPU sand budget in the WebGL2 plate.',
    type: 'number',
    min: 32768,
    max: 2097152,
    step: 1,
    numericScale: 'powerOfTwo',
    default: 262144,
    visibleRenderStyles: ['ultra'],
  },
  {
    key: 'rawParticleDensity',
    label: 'Particle Density',
    section: 'Rendering',
    description: 'Fine-tunes how tightly GPU sand grains pack around resonance lines.',
    type: 'number',
    min: 0.35,
    max: 8,
    step: 0.05,
    default: 1.25,
    visibleRenderStyles: ['ultra'],
  },
  {
    key: 'rawEmitterLimit',
    label: 'Source Limit',
    section: 'Input Mode',
    description: 'Caps how many placed resonance sources the WebGL2 plate can hold.',
    type: 'number',
    min: 1,
    max: 16,
    step: 1,
    default: 10,
  },
  {
    key: 'rawLineSharpness',
    label: 'Line Sharpness',
    section: 'Rendering',
    description: 'Narrows or softens the Chladni nodal bands in the raw shader.',
    type: 'number',
    min: 0,
    max: 3.5,
    step: 0.05,
    default: 1.8,
    visibleRenderStyles: ['ultra'],
  },
  {
    key: 'rawGlow',
    label: 'Glow',
    section: 'Rendering',
    description: 'Boosts the bloom-like energy halo around resonant sand ridges.',
    type: 'number',
    min: 0.25,
    max: 30,
    step: 0.05,
    default: 1.35,
    visibleRenderStyles: ['ultra'],
  },
];

export const HARMONIC_SAND_DEFAULTS: Record<string, unknown> = {
  resolution: 128,
  renderStyle: 'ultra',
  baseFrequency: 2.4,
  wavePeriod: 1,
  rawParticleCount: 262144,
  rawParticleDensity: 1.25,
  rawEmitterLimit: 10,
  rawLineSharpness: 1.8,
  rawGlow: 1.35,
  emitterCount: 0,
  style: 'chladni-gold',
  debug: false,
  screensaverMs: 60_000,
};
