import type { AmbientDefinition } from '@hooksjam/pixi-lab-core';
import { DEFAULT_AMBIENT_BEHAVIOR } from '@hooksjam/pixi-lab-core';
import { HOUSE_PULSE_MAP_DEFAULTS } from './house-pulse-map.config.js';
import { HousePulseMapScene, housePulseMapStyles } from './HousePulseMapScene.js';

export const housePulseMapDefinition: AmbientDefinition = {
  id: 'house-pulse-map',
  kind: 'ambient',
  renderModes: ['fullscreen', 'background', 'widget', 'previewTile'],
  name: 'House Pulse Map',
  short: 'A synthetic smart-home floorplan that glows with occupancy, energy, and event pulses.',
  long: 'House Pulse Map visualizes optional Home Assistant and presence snapshots as a deterministic floorplan of room nodes and event pulses. Synthetic fallback data keeps the ambient demoable without live integrations, while budgets, sensitivity, brightness, low-motion, and sleep controls apply live.',
  tags: ['ambient', 'background', 'home', 'presence', 'dashboard', 'low-motion'],
  icon: '🏠',
  paletteHint: 'neon-floorplan',
  capabilities: {
    ambient: true,
    ambientLayer: true,
    tutorial: true,
    reset: true,
    debugOverlay: true,
    styleExport: true,
    lowMotion: true,
    sleepMode: true,
    qualityModes: ['basic', 'enhanced'],
    settings: true,
  },
  dataBindings: [
    { source: 'homeAssistant', optional: true, fallback: 'synthetic' },
    { source: 'presence', optional: true, fallback: 'synthetic' },
    { source: 'time', optional: true, fallback: 'synthetic' },
    { source: 'synthetic', optional: false, fallback: 'idle' },
  ],
  behavior: {
    ...DEFAULT_AMBIENT_BEHAVIOR,
    maxBrightness: HOUSE_PULSE_MAP_DEFAULTS.maxBrightness,
    maxParticleCount: HOUSE_PULSE_MAP_DEFAULTS.nodeCount + HOUSE_PULSE_MAP_DEFAULTS.connectionCount,
    maxUpdateHz: 30,
    allowForeground: false,
    allowBackground: true,
  },
  styles: housePulseMapStyles,
  configDefaults: { ...HOUSE_PULSE_MAP_DEFAULTS },
  settingsFields: [
    {
      key: 'nodeCount',
      label: 'Room Nodes',
      description: 'Seeded smart-home node budget for rooms, devices, and zones.',
      type: 'number',
      min: 24,
      max: 420,
      step: 12,
      default: HOUSE_PULSE_MAP_DEFAULTS.nodeCount,
    },
    {
      key: 'connectionCount',
      label: 'Pulse Links',
      description: 'Animated event path budget connecting rooms and devices.',
      type: 'number',
      min: 24,
      max: 720,
      step: 12,
      default: HOUSE_PULSE_MAP_DEFAULTS.connectionCount,
    },
    {
      key: 'intensity',
      label: 'Intensity',
      description: 'Global brightness and activity multiplier for the passive map.',
      type: 'number',
      min: 0.08,
      max: 1,
      step: 0.04,
      default: HOUSE_PULSE_MAP_DEFAULTS.intensity,
    },
    {
      key: 'maxBrightness',
      label: 'Max Brightness',
      description: 'Caps node and pulse highlights for room-safe dashboards.',
      type: 'number',
      min: 0.1,
      max: 0.72,
      step: 0.04,
      default: HOUSE_PULSE_MAP_DEFAULTS.maxBrightness,
    },
    {
      key: 'eventSensitivity',
      label: 'Event Sensitivity',
      description: 'Controls how strongly Home Assistant activity changes visible pulses.',
      type: 'number',
      min: 0,
      max: 1,
      step: 0.05,
      default: HOUSE_PULSE_MAP_DEFAULTS.eventSensitivity,
    },
    {
      key: 'pulseSpeed',
      label: 'Pulse Speed',
      description: 'Adjusts how quickly activity pulses travel through the house map.',
      type: 'number',
      min: 0,
      max: 1,
      step: 0.05,
      default: HOUSE_PULSE_MAP_DEFAULTS.pulseSpeed,
    },
    {
      key: 'sleepMode',
      label: 'Sleep Mode',
      description: 'Dims and thins the house map for overnight use.',
      type: 'boolean',
      default: HOUSE_PULSE_MAP_DEFAULTS.sleepMode,
    },
    {
      key: 'lowMotion',
      label: 'Low Motion',
      description: 'Reduces pulse movement while preserving room status glimmers.',
      type: 'boolean',
      default: HOUSE_PULSE_MAP_DEFAULTS.lowMotion,
    },
  ],
  factory: () => new HousePulseMapScene(false),
  previewFactory: () => new HousePulseMapScene(true),
  defaultSeed: 8675309,
  tutorialPages: [
    {
      icon: '🏠',
      title: 'Home-aware, demo-safe',
      body: 'Optional Home Assistant and presence snapshots can drive occupancy, energy, event, and alert pulses, while synthetic fallback data keeps the ambient visible anywhere.',
    },
    {
      icon: '🧭',
      title: 'Deterministic floorplan',
      body: 'Room nodes, device links, pulse timing, and colors are seeded so preview and fullscreen sessions stay reproducible.',
    },
    {
      icon: '🌙',
      title: 'Passive display controls',
      body: 'Budgets, intensity, brightness, sensitivity, pulse speed, sleep mode, and low motion all apply while the scene is running.',
    },
  ],
};
