import type { SettingsField } from '@hooksjam/pixi-lab-core';

export const CHAIN_RAIN_SETTINGS_FIELDS: SettingsField[] = [
  {
    key: 'renderStyle',
    label: 'Style',
    section: 'Rendering',
    type: 'select',
    options: [
      { label: 'Basic', value: 'basic' },
      { label: 'Enhanced', value: 'enhanced' },
      { label: 'Ultra', value: 'ultra' },
    ],
    default: 'enhanced',
  },
  { key: 'maxNodes', label: 'Max Nodes', section: 'Physics', type: 'number', min: 2048, max: 131072, step: 1, numericScale: 'powerOfTwo', default: 32768, visibleQualities: ['raw'], advanced: true },
  { key: 'nodeRadius', label: 'Node Radius', section: 'Physics', type: 'number', min: 2, max: 12, step: 0.25, default: 5, visibleQualities: ['raw'] },
  { key: 'nodeVariance', label: 'Node Variance', section: 'Physics', type: 'number', min: 0, max: 1.5, step: 0.01, default: 0.28, visibleQualities: ['raw'] },
  { key: 'nodeVarianceWavelength', label: 'Variance Wavelength', section: 'Physics', type: 'number', min: 2, max: 48, step: 1, default: 14, visibleQualities: ['raw'], advanced: true },
  { key: 'nodeVarianceRoughness', label: 'Variance Roughness', section: 'Physics', type: 'number', min: 0, max: 1, step: 0.01, default: 0.35, visibleQualities: ['raw'], advanced: true },
  { key: 'chainLength', label: 'Chain Length', section: 'Input Mode', type: 'number', min: 3, max: 96, step: 1, default: 16, visibleQualities: ['raw'], visibleModes: ['draw'] },
  { key: 'interactionRadius', label: 'Interaction Radius', section: 'Input Mode', type: 'number', min: 16, max: 240, step: 2, default: 56, visibleQualities: ['raw'], visibleModes: ['interact'] },
  { key: 'gravity', label: 'Gravity', section: 'Physics', type: 'number', min: 0, max: 3000, step: 25, default: 1250, visibleQualities: ['raw'] },
  { key: 'friction', label: 'Friction', section: 'Physics', type: 'number', min: 0, max: 1, step: 0.01, default: 0.35, visibleQualities: ['raw'] },
  { key: 'solverPasses', label: 'Collision Passes', section: 'Physics', type: 'number', min: 1, max: 8, step: 1, default: 3, visibleQualities: ['raw'] },
  { key: 'substeps', label: 'Substeps', section: 'Physics', type: 'number', min: 1, max: 5, step: 1, default: 2, visibleQualities: ['raw'] },
  { key: 'constraintPasses', label: 'Link Passes', section: 'Physics', type: 'number', min: 1, max: 8, step: 1, default: 2, visibleQualities: ['raw'] },
  { key: 'constraintStiffness', label: 'Stiffness', section: 'Physics', type: 'number', min: 0.1, max: 1, step: 0.01, default: 0.92, visibleQualities: ['raw'] },
  { key: 'collisionSoftness', label: 'Softness', section: 'Physics', type: 'number', min: 0.05, max: 1.5, step: 0.01, default: 0.82, visibleQualities: ['raw'], advanced: true },
  { key: 'skinWidth', label: 'Skin Width', section: 'Rendering', type: 'number', min: 0.75, max: 2.4, step: 0.01, default: 1.08, visibleQualities: ['raw'], visibleRenderStyles: ['enhanced'] },
  { key: 'skinHighlightWidth', label: 'Highlight Width', section: 'Rendering', type: 'number', min: 0, max: 1.4, step: 0.01, default: 0.34, visibleQualities: ['raw'], visibleRenderStyles: ['enhanced'] },
  { key: 'skinHighlightStrength', label: 'Highlight Strength', section: 'Rendering', type: 'number', min: 0, max: 1.5, step: 0.01, default: 0.72, visibleQualities: ['raw'], visibleRenderStyles: ['enhanced'] },
  { key: 'skinHighlightOpacity', label: 'Highlight Opacity', section: 'Rendering', type: 'number', min: 0, max: 1, step: 0.01, default: 0.42, visibleQualities: ['raw'], visibleRenderStyles: ['enhanced'] },
  { key: 'liquidFieldScale', label: 'Liquid Resolution', section: 'Rendering', type: 'number', min: 0.35, max: 1.5, step: 0.01, default: 0.78, visibleQualities: ['raw'], visibleRenderStyles: ['ultra'] },
  { key: 'liquidParticleRadius', label: 'Liquid Radius', section: 'Rendering', type: 'number', min: 0.55, max: 7.5, step: 0.01, default: 1.45, visibleQualities: ['raw'], visibleRenderStyles: ['ultra'] },
  { key: 'liquidFillDensity', label: 'Bridge Fill', section: 'Rendering', type: 'number', min: 0, max: 3, step: 0.01, default: 1.1, visibleQualities: ['raw'], visibleRenderStyles: ['ultra'] },
  { key: 'liquidSplatDensity', label: 'Liquid Density', section: 'Rendering', type: 'number', min: 0.45, max: 2.5, step: 0.01, default: 1.14, visibleQualities: ['raw'], visibleRenderStyles: ['ultra'] },
  { key: 'liquidSurfaceThreshold', label: 'Surface Threshold', section: 'Rendering', type: 'number', min: 0.04, max: 0.42, step: 0.01, default: 0.16, visibleQualities: ['raw'], visibleRenderStyles: ['ultra'] },
  { key: 'liquidEdgeTightness', label: 'Edge Tightness', section: 'Rendering', type: 'number', min: 0, max: 1, step: 0.01, default: 0.76, visibleQualities: ['raw'], visibleRenderStyles: ['ultra'] },
  { key: 'liquidEdgeSoftness', label: 'Edge Softness', section: 'Rendering', type: 'number', min: 0, max: 1, step: 0.01, default: 0.46, visibleQualities: ['raw'], visibleRenderStyles: ['ultra'] },
  { key: 'liquidRefraction', label: 'Refraction', section: 'Rendering', type: 'number', min: 0, max: 1.5, step: 0.01, default: 0.58, visibleQualities: ['raw'], visibleRenderStyles: ['ultra'] },
  { key: 'liquidGloss', label: 'Specular Gloss', section: 'Rendering', type: 'number', min: 0, max: 1.5, step: 0.01, default: 0.68, visibleQualities: ['raw'], visibleRenderStyles: ['ultra'] },
  { key: 'liquidRimLighting', label: 'Rim Lighting', section: 'Rendering', type: 'number', min: 0, max: 2.5, step: 0.01, default: 0.72, visibleQualities: ['raw'], visibleRenderStyles: ['ultra'] },
  { key: 'liquidFoamStrength', label: 'Sparkle Foam', section: 'Rendering', type: 'number', min: 0, max: 3, step: 0.01, default: 0.34, visibleQualities: ['raw'], visibleRenderStyles: ['ultra'] },
  { key: 'liquidThermalStrength', label: 'Palette Flow', section: 'Rendering', type: 'number', min: 0, max: 1, step: 0.01, default: 0.42, visibleQualities: ['raw'], visibleRenderStyles: ['ultra'] },
  { key: 'liquidBloomStrength', label: 'Bloom', section: 'Rendering', type: 'number', min: 0, max: 3, step: 0.01, default: 0.26, visibleQualities: ['raw'], visibleRenderStyles: ['ultra'] },
  { key: 'liquidHeatShimmer', label: 'Heat Shimmer', section: 'Rendering', type: 'number', min: 0, max: 2, step: 0.01, default: 0.14, visibleQualities: ['raw'], visibleRenderStyles: ['ultra'] },
  { key: 'liquidDepthDiffusion', label: 'Depth Diffusion', section: 'Rendering', type: 'number', min: 0, max: 1, step: 0.01, default: 0.18, visibleQualities: ['raw'], visibleRenderStyles: ['ultra'] },
  { key: 'opacity', label: 'Opacity', section: 'Rendering', type: 'number', min: 0.2, max: 1, step: 0.01, default: 0.86, visibleQualities: ['raw'], visibleRenderStyles: ['ultra'] },
];

export const CHAIN_RAIN_DEFAULTS: Record<string, unknown> = {
  renderStyle: 'enhanced',
  maxNodes: 32768,
  nodeRadius: 5,
  nodeVariance: 0.28,
  nodeVarianceWavelength: 14,
  nodeVarianceRoughness: 0.35,
  chainLength: 16,
  interactionRadius: 56,
  gravity: 1250,
  friction: 0.35,
  solverPasses: 3,
  substeps: 2,
  constraintPasses: 2,
  constraintStiffness: 0.92,
  collisionSoftness: 0.82,
  skinWidth: 1.08,
  skinHighlightWidth: 0.34,
  skinHighlightStrength: 0.72,
  skinHighlightOpacity: 0.42,
  liquidFieldScale: 0.78,
  liquidParticleRadius: 1.45,
  liquidFillDensity: 1.1,
  liquidSplatDensity: 1.14,
  liquidSurfaceThreshold: 0.16,
  liquidEdgeTightness: 0.76,
  liquidEdgeSoftness: 0.46,
  liquidRefraction: 0.58,
  liquidGloss: 0.68,
  liquidRimLighting: 0.72,
  liquidFoamStrength: 0.34,
  liquidThermalStrength: 0.42,
  liquidBloomStrength: 0.26,
  liquidHeatShimmer: 0.14,
  liquidDepthDiffusion: 0.18,
  opacity: 0.86,
};
