import { createEngineConfigurations, DEFAULT_FOREGROUND_BEHAVIOR, type EffectDefinition } from '@hooksjam/pixi-lab-core';
import { EMBERS_DEFAULTS } from './embers.config.js';
import { EmbersScene, embersStyleManifest } from './EmbersScene.js';

export const embersDefinition: EffectDefinition = {
  id: 'embers',
  kind: 'effect',
  renderModes: ['foregroundOverlay', 'fullscreen', 'previewTile'],
  name: 'Embers',
  short: 'A cozy foreground ember overlay with deterministic sparks and synthetic heat fallback.',
  long: 'Embers is a transparent foreground overlay for dashboards and ambient gallery use. It uses deterministic seeded sparks, optional Home Assistant/weather snapshots, and synthetic fallback data so cozy mode remains demoable without live integrations.',
  tags: ['effect', 'overlay', 'cozy', 'seasonal', 'low-motion'],
  icon: '🔥',
  paletteHint: 'hearth-glow',
  capabilities: {
    reset: true,
    debugOverlay: true,
    styleExport: true,
    lowMotion: true,
    sleepMode: true,
    engineConfigurations: createEngineConfigurations(['basic', 'enhanced']),
    settings: true,
  },
  dataBindings: [
    { source: 'homeAssistant', optional: true, fallback: 'synthetic' },
    { source: 'weather', optional: true, fallback: 'synthetic' },
    { source: 'synthetic', optional: false, fallback: 'idle' },
  ],
  behavior: {
    ...DEFAULT_FOREGROUND_BEHAVIOR,
    maxBrightness: EMBERS_DEFAULTS.maxBrightness,
    maxParticleCount: EMBERS_DEFAULTS.emberCount,
  },
  configDefaults: { ...EMBERS_DEFAULTS },
  styleManifest: embersStyleManifest,
  settingsFields: [
    {
      key: 'emberCount',
      label: 'Ember Count',
      description: 'Seeded particle budget for the foreground overlay.',
      type: 'number',
      min: 24,
      max: 1000,
      step: 24,
      default: EMBERS_DEFAULTS.emberCount,
    },
    {
      key: 'intensity',
      label: 'Intensity',
      description: 'Global ember brightness and motion multiplier.',
      type: 'number',
      min: 0.08,
      max: 1,
      step: 0.04,
      default: EMBERS_DEFAULTS.intensity,
    },
    {
      key: 'maxBrightness',
      label: 'Max Brightness',
      description: 'Caps ember alpha so the overlay stays foreground-safe.',
      type: 'number',
      min: 0.12,
      max: 0.85,
      step: 0.04,
      default: EMBERS_DEFAULTS.maxBrightness,
    },
    {
      key: 'heat',
      label: 'Heat',
      description: 'Manual cozy heat mixed with Home Assistant or synthetic fallback data.',
      type: 'number',
      min: 0,
      max: 1,
      step: 0.04,
      default: EMBERS_DEFAULTS.heat,
    },
    {
      key: 'updraft',
      label: 'Updraft',
      description: 'Vertical lift and turbulence for rising sparks.',
      type: 'number',
      min: 0,
      max: 1,
      step: 0.04,
      default: EMBERS_DEFAULTS.updraft,
    },
    {
      key: 'sleepMode',
      label: 'Sleep Mode',
      description: 'Dims and thins embers for overnight passive displays.',
      type: 'boolean',
      default: EMBERS_DEFAULTS.sleepMode,
    },
    {
      key: 'lowMotion',
      label: 'Low Motion',
      description: 'Reduces rise speed and visible embers while preserving the cozy read.',
      type: 'boolean',
      default: EMBERS_DEFAULTS.lowMotion,
    },
  ],
  factory: () => new EmbersScene(false),
  previewFactory: () => new EmbersScene(true),
  defaultSeed: 20261225,
  tutorialPages: [
    {
      icon: '🔥',
      title: 'Cozy foreground sparks',
      body: 'Embers is designed for transparent overlays and keeps brightness capped so UI remains readable.',
    },
    {
      icon: '🏠',
      title: 'Smart-home optional',
      body: 'Home Assistant and weather snapshots can shape heat and activity, but synthetic fallback data keeps the gallery demoable without integrations.',
    },
    {
      icon: '🌙',
      title: 'Passive controls',
      body: 'Ember budget, intensity, brightness, heat, updraft, sleep mode, and low motion all apply while the scene runs.',
    },
  ],
};
