export type ColorPitPhase = 'start' | 'play' | 'result';
export type ColorPitColorId = 'cyan' | 'pink' | 'yellow' | 'green';

export interface ColorPitSettings { roundBalls: number; spawnCadence: number; gravity: number; overflowLimit: number }
export interface ColorPitLane { id: ColorPitColorId; x: number; width: number; color: number; label: string }
export interface ColorPitBall { id: string; colorId: ColorPitColorId; x: number; y: number; vx: number; vy: number; radius: number; color: number; targetLaneId: ColorPitColorId }
export interface ColorPitBoardBounds { left: number; top: number; right: number; bottom: number; width: number; height: number }
export interface ColorPitResult { outcome: 'complete' | 'bust'; finalScore: number; label: string }
export interface ColorPitState { phase: ColorPitPhase; width: number; height: number; board: ColorPitBoardBounds; score: number; streak: number; spawned: number; remaining: number; overflow: number; settings: ColorPitSettings; lanes: readonly ColorPitLane[]; activeBalls: readonly ColorPitBall[]; result: ColorPitResult | null }
export type ColorPitVisualEvent = { kind: 'score'; ballId: string; matched: boolean; points: number; streak: number; x: number; y: number; color: number } | { kind: 'state'; phase: ColorPitPhase };
export interface ColorPitModelOptions { seed: number; width: number; height: number; roundBalls?: number; spawnCadence?: number; gravity?: number; overflowLimit?: number; preview?: boolean }
interface MutableBall extends ColorPitBall {}
const COLOR_ORDER: ColorPitColorId[] = ['cyan','pink','yellow','green'];
const COLOR_META: Record<ColorPitColorId,{color:number;label:string}> = { cyan:{color:0x22d3ee,label:'CYAN'}, pink:{color:0xf472b6,label:'PINK'}, yellow:{color:0xfacc15,label:'GOLD'}, green:{color:0x34d399,label:'LIME'} };
function mulberry32(seed:number):()=>number{let state=seed>>>0;return()=>{state+=0x6d2b79f5;let t=state;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296}}
function clamp(value:number,min:number,max:number):number{return Math.min(max,Math.max(min,value))}
function sanitizeSettings(settings: ColorPitSettings): ColorPitSettings {
  return {
    roundBalls: Math.round(clamp(settings.roundBalls, 12, 72)),
    spawnCadence: clamp(settings.spawnCadence, 0.35, 1.4),
    gravity: clamp(settings.gravity, 320, 880),
    overflowLimit: Math.round(clamp(settings.overflowLimit, 3, 16)),
  };
}
function cloneBall(ball:MutableBall):ColorPitBall{return{...ball}}
export class ColorPitModel{
  private readonly rng:()=>number; private readonly board:ColorPitBoardBounds; private readonly lanes:ColorPitLane[]; private readonly balls=new Map<string,MutableBall>(); private readonly events:ColorPitVisualEvent[]=[]; private settings:ColorPitSettings; private phase:ColorPitPhase='start'; private score=0; private streak=0; private spawned=0; private overflow=0; private elapsedPlay=0; private nextBall=1; private result:ColorPitResult|null=null;
  constructor(private readonly options:Required<ColorPitModelOptions>){this.rng=mulberry32(options.seed);this.settings=sanitizeSettings({roundBalls:options.roundBalls,spawnCadence:options.spawnCadence,gravity:options.gravity,overflowLimit:options.overflowLimit});this.board=this.createBoardBounds();this.lanes=this.createLanes()}
  getState():ColorPitState{return{phase:this.phase,width:this.options.width,height:this.options.height,board:{...this.board},score:this.score,streak:this.streak,spawned:this.spawned,remaining:Math.max(0,this.settings.roundBalls-this.spawned),overflow:this.overflow,settings:{...this.settings},lanes:this.lanes.map(lane=>({...lane})),activeBalls:Array.from(this.balls.values(),cloneBall),result:this.result?{...this.result}:null}}
  updateSettings(next:Partial<ColorPitSettings>):void{const previous=this.settings.roundBalls;this.settings=sanitizeSettings({roundBalls:next.roundBalls??this.settings.roundBalls,spawnCadence:next.spawnCadence??this.settings.spawnCadence,gravity:next.gravity??this.settings.gravity,overflowLimit:next.overflowLimit??this.settings.overflowLimit});if(next.roundBalls!==undefined&&this.phase==='play'){this.spawned=Math.min(this.spawned,this.settings.roundBalls);if(previous!==this.settings.roundBalls)this.maybeFinish()}if(next.roundBalls!==undefined&&this.phase==='start')this.spawned=0;if(next.overflowLimit!==undefined&&this.overflow>=this.settings.overflowLimit&&this.phase==='play')this.finish('bust')}
  spawnBall(normalizedX=0.5):ColorPitBall{if(this.phase==='result'||this.spawned>=this.settings.roundBalls)throw new Error('No color pit balls remaining');const colorId=COLOR_ORDER[Math.floor(this.rng()*COLOR_ORDER.length)%COLOR_ORDER.length];const lane=this.lanes.find(candidate=>candidate.id===colorId)??this.lanes[0];const radius=this.options.preview?clamp(this.options.width*0.028,4,8):clamp(this.options.width*0.018,10,18);const x=clamp(normalizedX,0,1)*this.options.width;const ball:MutableBall={id:`color-ball-${this.nextBall++}`,colorId,x:clamp(x,this.board.left+radius,this.board.right-radius),y:this.board.top+radius,vx:(lane.x+lane.width/2-x)*0.22+(this.rng()-0.5)*130,vy:35+this.rng()*55,radius,color:COLOR_META[colorId].color,targetLaneId:colorId};this.balls.set(ball.id,ball);this.spawned+=1;this.setPhase('play');return cloneBall(ball)}
  nudgeToward(ballId:string,normalizedX:number):void{const ball=this.balls.get(ballId);if(!ball)return;const targetX=clamp(normalizedX,0,1)*this.options.width;ball.vx+=clamp((targetX-ball.x)*2.6,-150,150)}
  nudgeNearest(normalizedX:number):void{const targetX=clamp(normalizedX,0,1)*this.options.width;let nearest:MutableBall|null=null;let nearestDistance=Number.POSITIVE_INFINITY;for(const ball of this.balls.values()){const distance=Math.abs(ball.x-targetX)+ball.y*0.02;if(distance<nearestDistance){nearest=ball;nearestDistance=distance}}if(nearest)this.nudgeToward(nearest.id,normalizedX)}
  step(dt:number):void{if(this.phase!=='play')return;const seconds=clamp(dt,0,1/20);this.elapsedPlay+=seconds;for(const ball of Array.from(this.balls.values())){ball.vy+=this.settings.gravity*seconds;ball.vx*=0.997;ball.x+=ball.vx*seconds;ball.y+=ball.vy*seconds;this.collideWalls(ball);this.collideBalls(ball);if(ball.y+ball.radius>=this.board.bottom)this.resolveBall(ball.id)}this.maybeFinish()}
  restart():void{this.balls.clear();this.score=0;this.streak=0;this.spawned=0;this.overflow=0;this.elapsedPlay=0;this.nextBall=1;this.result=null;this.setPhase('start')}
  drainEvents():ColorPitVisualEvent[]{return this.events.splice(0,this.events.length)}
  private resolveBall(ballId:string):void{const ball=this.balls.get(ballId);if(!ball)return;const lane=this.findLane(ball.x);const matched=lane.id===ball.targetLaneId;if(matched){this.streak+=1;const points=10+this.streak*2;this.score+=points;this.events.push({kind:'score',ballId,matched,points,streak:this.streak,x:ball.x,y:this.board.bottom,color:ball.color})}else{this.streak=0;this.overflow+=1;this.events.push({kind:'score',ballId,matched,points:0,streak:0,x:ball.x,y:this.board.bottom,color:0xef4444})}this.balls.delete(ballId);if(this.overflow>=this.settings.overflowLimit)this.finish('bust');else this.maybeFinish()}
  private maybeFinish():void{if(this.phase!=='play')return;if(this.spawned<this.settings.roundBalls||this.balls.size>0)return;this.finish('complete')}
  private finish(outcome:ColorPitResult['outcome']):void{if(this.phase==='result')return;if(this.elapsedPlay<6)return;if(outcome==='complete'&&this.spawned<12)return;this.result={outcome,finalScore:this.score,label:outcome==='bust'?'Overflow!':this.score>=this.settings.roundBalls*14?'Perfect Flow':this.score>=this.settings.roundBalls*9?'Clean Sort':'Sorting Run'};this.setPhase('result')}
  private setPhase(phase:ColorPitPhase):void{if(this.phase===phase)return;this.phase=phase;this.events.push({kind:'state',phase})}
  private createBoardBounds():ColorPitBoardBounds{const horizontalMargin=this.options.preview?0:clamp(this.options.width*0.06,28,88);const top=this.options.preview?0:clamp(this.options.height*0.16,112,144);const bottomMargin=this.options.preview?clamp(this.options.height*0.18,36,70):clamp(this.options.height*0.13,88,132);const bottom=this.options.height-bottomMargin;const left=horizontalMargin;const right=this.options.width-horizontalMargin;return{left,top,right,bottom,width:right-left,height:bottom-top}}
  private createLanes():ColorPitLane[]{const width=this.board.width/COLOR_ORDER.length;return COLOR_ORDER.map((id,index)=>({id,x:this.board.left+index*width,width,color:COLOR_META[id].color,label:COLOR_META[id].label}))}
  private findLane(x:number):ColorPitLane{return this.lanes.find(lane=>x>=lane.x&&x<lane.x+lane.width)??this.lanes[this.lanes.length-1]}
  private collideWalls(ball:MutableBall):void{if(ball.x<this.board.left+ball.radius){ball.x=this.board.left+ball.radius;ball.vx=Math.abs(ball.vx)*0.72}if(ball.x>this.board.right-ball.radius){ball.x=this.board.right-ball.radius;ball.vx=-Math.abs(ball.vx)*0.72}}
  private collideBalls(ball:MutableBall):void{for(const other of this.balls.values()){if(other.id===ball.id)continue;const dx=ball.x-other.x;const dy=ball.y-other.y;const min=ball.radius+other.radius;const distSq=dx*dx+dy*dy;if(distSq<=0.0001||distSq>=min*min)continue;const dist=Math.sqrt(distSq);const nx=dx/dist;const ny=dy/dist;const overlap=(min-dist)*0.5;ball.x+=nx*overlap;ball.y+=ny*overlap;other.x-=nx*overlap;other.y-=ny*overlap;const push=18;ball.vx+=nx*push;ball.vy+=ny*push;other.vx-=nx*push;other.vy-=ny*push}}
}
export function createColorPitModel(options:ColorPitModelOptions):ColorPitModel{return new ColorPitModel({seed:options.seed,width:options.width,height:options.height,roundBalls:options.roundBalls??(options.preview?18:36),spawnCadence:options.spawnCadence??(options.preview?0.62:0.72),gravity:options.gravity??(options.preview?420:520),overflowLimit:options.overflowLimit??(options.preview?99:8),preview:options.preview??false})}
