import { Container, Graphics, Text } from 'pixi.js';
import { Scene, type GameContext, type Input, type RenderQuality } from '@hooksjam/pixi-lab-core';
import { COLOR_PIT_DEFAULTS } from './color-pit-arena.config';
import { createColorPitModel, type ColorPitModel, type ColorPitSettings, type ColorPitState, type ColorPitVisualEvent } from './ColorPitModel';
interface FloatingText { text: Text; life: number; vy: number }
interface Spark { x: number; y: number; vx: number; vy: number; color: number; life: number; maxLife: number }
function clamp(value: number, min: number, max: number): number { return Math.min(max, Math.max(min, value)); }
function numberSetting(value: unknown, fallback: number, min: number, max: number): number {
  const numeric = Number(value ?? fallback);
  return Number.isFinite(numeric) ? clamp(numeric, min, max) : fallback;
}
export class ColorPitScene extends Scene {
  readonly name: string = 'ColorPitArena'; private root=new Container(); private boardLayer=new Graphics(); private ballLayer=new Graphics(); private effectLayer=new Graphics(); private overlayLayer=new Graphics(); private labelLayer=new Container(); private model:ColorPitModel|null=null; private state:ColorPitState|null=null; private spawnElapsed=0; private handledDownIds=new Set<number>(); private floatingTexts:FloatingText[]=[]; private sparks:Spark[]=[]; private dirty=true; private boardDirty=true; private quality:RenderQuality='basic'; private appliedSettings:ColorPitSettings={...COLOR_PIT_DEFAULTS};
  constructor(private readonly preview=false){super()}
  onEnter(ctx:GameContext,input:Input):void{this.ctx=ctx;this.input=input;this.quality=ctx.quality;ctx.systems.pixi.stage.addChild(this.root);this.root.addChild(this.boardLayer,this.ballLayer,this.effectLayer,this.overlayLayer,this.labelLayer);this.createModel(ctx.width,ctx.height)}
  onExit():void{this.root.removeFromParent();this.root.destroy({children:true});this.floatingTexts=[];this.sparks=[];this.model=null;this.state=null}
  override resize(width:number,height:number):void{this.createModel(width,height)}
  override reset():void{this.model?.restart();this.spawnElapsed=0;this.handledDownIds.clear();this.floatingTexts.forEach(entry=>entry.text.destroy());this.floatingTexts=[];this.sparks=[];if(this.preview)this.spawnPreviewBall();this.handleEvents();this.refreshState()}
  override setQuality(quality:RenderQuality):void{this.quality=quality;this.boardDirty=true;this.dirty=true}
  override fixedUpdate(dt:number):void{if(!this.model||!this.state)return;const seconds=clamp(dt,0,1/20);this.applyLiveSettings();if(this.state.phase!=='start')this.spawnElapsed+=seconds;if(this.state.phase!=='result'&&(this.state.phase==='play'||this.preview)){const cadence=this.preview?0.72:this.appliedSettings.spawnCadence;if(this.spawnElapsed>=cadence){this.spawnElapsed-=cadence;this.spawnBallAt(this.nextSpawnX())}}for(const id of Array.from(this.handledDownIds)){if(!this.input.snapshot.justDown.has(id))this.handledDownIds.delete(id)}for(const id of this.input.snapshot.justDown){if(this.handledDownIds.has(id))continue;this.handledDownIds.add(id);const pointer=this.input.snapshot.pointers.get(id);if(!pointer)continue;if(this.state.phase==='start')this.spawnBallAt(pointer.x/Math.max(1,this.state.width));else this.model.nudgeNearest(pointer.x/Math.max(1,this.state.width))}for(const pointer of this.input.snapshot.pointers.values()){if(pointer.type==='move'&&this.state.phase==='start'){this.spawnBallAt(pointer.x/Math.max(1,this.state.width));break}}if(this.state.phase==='play'){this.model.step(seconds);this.handleEvents();this.refreshState()}}
  override update(dt:number):void{const had=this.sparks.length>0||this.floatingTexts.length>0;for(const spark of this.sparks){spark.life-=dt;spark.x+=spark.vx*dt;spark.y+=spark.vy*dt;spark.vy+=80*dt}this.sparks=this.sparks.filter(spark=>spark.life>0).slice(-(this.preview?50:180));for(const floating of this.floatingTexts){floating.life-=dt;floating.text.y+=floating.vy*dt;floating.text.alpha=Math.max(0,floating.life/0.9)}for(const floating of this.floatingTexts.filter(entry=>entry.life<=0)){floating.text.removeFromParent();floating.text.destroy()}this.floatingTexts=this.floatingTexts.filter(entry=>entry.life>0);if(had||this.sparks.length>0||this.floatingTexts.length>0)this.dirty=true}
  override render():void{if(!this.state||(!this.dirty&&!this.boardDirty))return;if(this.boardDirty){this.drawBoard(this.state);this.boardDirty=false}if(this.dirty){this.drawBalls(this.state);this.drawOverlay(this.state);this.dirty=false}}
  override shouldRender():boolean{return this.boardDirty||this.dirty||Boolean(this.state?.activeBalls.length)||this.sparks.length>0||this.floatingTexts.length>0}
  override getDebugStats():Record<string,string|number|boolean|null>|null{if(!this.state)return null;return{gameState:this.state.phase,score:this.state.score,streak:this.state.streak,remaining:this.state.remaining,overflow:this.state.overflow,quality:this.quality}}
  private readRuleSettings():ColorPitSettings{const settings=this.ctx.systems.settings;if(this.preview)return{roundBalls:24,spawnCadence:0.72,gravity:420,overflowLimit:99};return{roundBalls:numberSetting(settings.get('roundBalls'),COLOR_PIT_DEFAULTS.roundBalls,12,72),spawnCadence:numberSetting(settings.get('spawnCadence'),COLOR_PIT_DEFAULTS.spawnCadence,0.35,1.4),gravity:numberSetting(settings.get('gravity'),COLOR_PIT_DEFAULTS.gravity,320,880),overflowLimit:numberSetting(settings.get('overflowLimit'),COLOR_PIT_DEFAULTS.overflowLimit,3,16)}}
  private createModel(width:number,height:number):void{this.appliedSettings=this.readRuleSettings();this.model=createColorPitModel({seed:this.ctx.seed,width,height,preview:this.preview,...this.appliedSettings});this.spawnElapsed=0;this.boardDirty=true;if(this.preview)this.spawnPreviewBall();this.handleEvents();this.refreshState()}
  private applyLiveSettings():void{if(!this.model)return;const next=this.readRuleSettings();if(next.roundBalls===this.appliedSettings.roundBalls&&next.spawnCadence===this.appliedSettings.spawnCadence&&next.gravity===this.appliedSettings.gravity&&next.overflowLimit===this.appliedSettings.overflowLimit)return;this.model.updateSettings(next);this.appliedSettings=next;this.refreshState()}
  private nextSpawnX():number{const active=this.model?.getState().activeBalls.length??0;return 0.18+((active*0.23+this.spawnElapsed*0.11)%0.64)}
  private spawnPreviewBall():void{this.spawnBallAt(0.5)} private spawnBallAt(normalizedX:number):void{if(!this.model)return;try{this.model.spawnBall(normalizedX);this.handleEvents();this.refreshState()}catch{/** Round exhausted; model result flow handles idle state. */}}
  private refreshState():void{this.state=this.model?.getState()??null;if(this.state?.phase==='result'&&this.state.score<=12){this.model?.restart();this.state=this.model?.getState()??null}if(this.state){this.ctx.emit({kind:'score_update',value:this.state.score,payload:{streak:this.state.streak,remaining:this.state.remaining,overflow:this.state.overflow,phase:this.state.phase}});if(this.state.phase==='result')this.ctx.emit({kind:'game_over',value:this.state.score,payload:{outcome:this.state.result?.outcome??'complete',label:this.state.result?.label??'Round Complete'}})}this.dirty=true}
  private handleEvents():void{const events=this.model?.drainEvents()??[];for(const event of events)this.applyVisualEvent(event)}
  private applyVisualEvent(event:ColorPitVisualEvent):void{if(event.kind==='score'&&!this.preview){const text=new Text({text:event.matched?`+${event.points}`:'MISS',style:{fill:event.color,fontFamily:'Inter, system-ui, sans-serif',fontSize:22,fontWeight:'900',stroke:{color:0x020617,width:4}}});text.anchor.set(0.5);text.position.set(event.x,event.y-26);this.root.addChild(text);this.floatingTexts.push({text,life:0.9,vy:-38});const count=event.matched?12:5;for(let i=0;i<count;i+=1){const angle=(Math.PI*2*i)/count;this.sparks.push({x:event.x,y:event.y,vx:Math.cos(angle)*(50+event.streak*4),vy:Math.sin(angle)*55-35,color:event.color,life:0.55,maxLife:0.55})}}this.dirty=true}
  private drawBoard(state:ColorPitState):void{this.boardLayer.clear();this.labelLayer.removeChildren().forEach(child=>child.destroy());this.boardLayer.rect(0,0,state.width,state.height);this.boardLayer.fill({color:0x050816});this.boardLayer.roundRect(state.board.left,state.board.top,state.board.width,state.board.height,this.preview?0:28);this.boardLayer.fill({color:0x0f172a,alpha:0.72});this.boardLayer.stroke({color:0x334155,width:4,alpha:0.82});const funnelTop=state.board.top+state.board.height*0.12;const funnelBottom=state.board.bottom;for(const lane of state.lanes){this.boardLayer.rect(lane.x,funnelBottom,lane.width,state.height-funnelBottom);this.boardLayer.fill({color:lane.color,alpha:0.18});this.boardLayer.stroke({color:lane.color,width:3,alpha:0.76});this.boardLayer.moveTo(lane.x+lane.width/2,funnelTop);this.boardLayer.lineTo(lane.x+lane.width/2,funnelBottom);this.boardLayer.stroke({color:lane.color,width:2,alpha:0.18});if(!this.preview){const label=new Text({text:lane.label,style:{fill:0xffffff,fontFamily:'Inter, system-ui, sans-serif',fontSize:clamp(lane.width*0.14,16,26),fontWeight:'900',stroke:{color:0x020617,width:4}}});label.anchor.set(0.5);label.position.set(lane.x+lane.width/2,funnelBottom+Math.max(36,(state.height-funnelBottom)*0.38));this.labelLayer.addChild(label)}}}
  private drawBalls(state:ColorPitState):void{this.ballLayer.clear();this.effectLayer.clear();for(const ball of state.activeBalls){this.ballLayer.circle(ball.x,ball.y,ball.radius+9);this.ballLayer.fill({color:ball.color,alpha:0.18});this.ballLayer.circle(ball.x,ball.y,ball.radius);this.ballLayer.fill({color:ball.color,alpha:1});this.ballLayer.circle(ball.x-ball.radius*0.28,ball.y-ball.radius*0.34,ball.radius*0.25);this.ballLayer.fill({color:0xffffff,alpha:0.58})}for(const spark of this.sparks){const alpha=Math.max(0,spark.life/spark.maxLife);this.effectLayer.circle(spark.x,spark.y,2+alpha*3);this.effectLayer.fill({color:spark.color,alpha})}}
  private drawOverlay(state:ColorPitState):void{this.overlayLayer.clear();if(state.phase==='start'){this.overlayLayer.roundRect(state.board.left+state.board.width*0.2,state.board.top+state.board.height*0.36,state.board.width*0.6,state.board.height*0.16,24);this.overlayLayer.fill({color:0x020617,alpha:0.42});this.overlayLayer.stroke({color:0x22d3ee,width:2,alpha:0.55})}if(state.phase==='result'){this.overlayLayer.roundRect(state.board.left+state.board.width*0.18,state.board.top+state.board.height*0.28,state.board.width*0.64,state.board.height*0.22,24);this.overlayLayer.fill({color:0x020617,alpha:0.58});this.overlayLayer.stroke({color:state.result?.outcome==='bust'?0xef4444:0x34d399,width:3,alpha:0.8})}}
}
