import type { SettingsField } from '@hooksjam/pixi-lab-core';
import { sparkSizeVariabilityField } from '../shared/spark-rendering.js';

const SPARK_EMITTER_MODES = ['welding', 'pinwheel', 'shower'];

export const SPARKS_SETTINGS_FIELDS: SettingsField[] = [
  { key: 'emissionRate', label: 'Burst Rate', section: 'Input Mode', description: 'Controls how often emitter contacts emit spark bursts. Burst Density controls how many sparks are in each burst.', type: 'number', min: 0, max: 80000, step: 25, default: 980, visibleModes: SPARK_EMITTER_MODES },
  { key: 'sparkPower', label: 'Spark Power', section: 'Input Mode', type: 'number', min: 90, max: 6000, step: 25, default: 480, visibleModes: SPARK_EMITTER_MODES },
  { key: 'sparkDirectionChaos', label: 'Direction Chaos', section: 'Input Mode', description: 'Varies the initial direction of emitted sparks.', type: 'number', min: 0, max: 1, step: 0.01, default: 0.42, visibleModes: SPARK_EMITTER_MODES },
  { key: 'torchRadius', label: 'Torch Radius', section: 'Input Mode', type: 'number', min: 4, max: 56, step: 1, default: 24, visibleModes: SPARK_EMITTER_MODES },
  { key: 'buildRadius', label: 'Build Radius', section: 'Input Mode', type: 'number', min: 10, max: 44, step: 1, default: 18, visibleModes: ['build'] },
  { key: 'contactHeat', label: 'Burst Density', section: 'Input Mode', description: 'Controls sparks per burst and white-hot core intensity at the emitter contact. Burst Rate controls cadence.', type: 'number', min: 0, max: 12, step: 0.05, default: 2.1, visibleModes: SPARK_EMITTER_MODES },
  { key: 'coreFlashRate', label: 'Core Flash Rate', section: 'Input Mode', description: 'Controls how often the white-hot source flashes between spark bursts.', type: 'number', min: 0, max: 18, step: 0.05, default: 3.2, visibleModes: SPARK_EMITTER_MODES },
  { key: 'coreFlashSize', label: 'Core Flash Size', section: 'Input Mode', description: 'Scales the compact white-hot source flashes separately from flying sparks.', type: 'number', min: 0.02, max: 2.4, step: 0.01, default: 1, visibleModes: SPARK_EMITTER_MODES },
  { key: 'coreFlashVariability', label: 'Core Flash Variability', section: 'Input Mode', description: 'Varies core flash timing, particle count, and brightness from burst to burst.', type: 'number', min: 0, max: 1, step: 0.01, default: 0.56, visibleModes: SPARK_EMITTER_MODES },
  { key: 'coreIntensity', label: 'Core Brightness', section: 'Input Mode', description: 'Controls the white-hot source brightness separately from spark size.', type: 'number', min: 0.15, max: 8, step: 0.05, default: 3.65, visibleModes: SPARK_EMITTER_MODES },
  { key: 'coreAfterglow', label: 'Core Afterglow', section: 'Input Mode', description: 'Controls how long the white-hot source flash persists into the glow and trail layers.', type: 'number', min: 0, max: 1, step: 0.01, default: 0.38, visibleModes: SPARK_EMITTER_MODES },
  { key: 'bounceRestitution', label: 'Bounce', section: 'Physics', type: 'number', min: 0, max: 1.35, step: 0.01, default: 0.58 },
  { key: 'splitChance', label: 'Shard Split Chance', section: 'Physics', description: 'Chance that a bounced spark mutates into a sharper child shard and seeds secondary bounce sparks.', type: 'number', min: 0, max: 1, step: 0.01, default: 0.46 },
  { key: 'maxSplits', label: 'Shard Depth', section: 'Physics', type: 'number', min: 0, max: 4, step: 1, default: 2 },
  { key: 'bounceBurstChance', label: 'Bounce Burst Chance', section: 'Physics', description: 'Chance that a bounced spark emits a secondary burst into available GPU particle slots.', type: 'number', min: 0, max: 1, step: 0.01, default: 0.38 },
  { key: 'bounceBurstCount', label: 'Bounce Burst Count', section: 'Physics', description: 'Controls how many secondary spark slots try to respawn from each marked bounce.', type: 'number', min: 0, max: 48, step: 1, default: 12 },
  { key: 'bounceBurstPower', label: 'Bounce Burst Power', section: 'Physics', description: 'Adds extra speed to secondary bounce bursts beyond the reflected parent velocity.', type: 'number', min: 0, max: 2600, step: 10, default: 520 },
  { key: 'bounceBurstSpread', label: 'Bounce Burst Spread', section: 'Physics', description: 'Widens the angle of secondary sparks emitted after a bounce.', type: 'number', min: 0, max: 3, step: 0.01, default: 1.08 },
  { key: 'sparkLifespan', label: 'Spark Lifespan', section: 'Physics', description: 'Scales how long core glow particles and flying sparks survive before fading out.', type: 'number', min: 0.2, max: 4, step: 0.05, default: 1 },
  { key: 'sparkLifespanVariability', label: 'Lifespan Variability', section: 'Physics', description: 'Varies each spark lifetime from its packed GPU particle seed.', type: 'number', min: 0, max: 1, step: 0.01, default: 0.34 },
  { key: 'sparkTurbulence', label: 'Turbulence', section: 'Physics', description: 'Adds coherent in-flight directional turbulence without applying drag.', type: 'number', min: 0, max: 1, step: 0.01, default: 0.26 },
  { key: 'gravity', label: 'Gravity', section: 'Physics', type: 'number', min: 80, max: 1300, step: 10, default: 640 },
  { key: 'airDrag', label: 'Air Drag', section: 'Physics', type: 'number', min: 0, max: 4, step: 0.05, default: 0.86 },
  { key: 'surfaceFriction', label: 'Surface Friction', section: 'Physics', type: 'number', min: 0, max: 0.85, step: 0.01, default: 0.18 },
  {
    key: 'simDepth',
    label: 'Simulation Depth',
    section: 'Physics',
    description: 'Optional pseudo-depth variation for spark scale and collision radius.',
    type: 'select',
    default: 'layered',
    options: [
      { label: 'Flat', value: 'flat' },
      { label: 'Layered', value: 'layered' },
      { label: 'Deep', value: 'deep' },
    ],
  },
  {
    key: 'renderStyle',
    label: 'Render Style',
    section: 'Rendering',
    type: 'select',
    default: 'enhanced',
    options: [
      { label: 'Basic', value: 'basic' },
      { label: 'Enhanced', value: 'enhanced' },
      { label: 'Ultra', value: 'ultra' },
    ],
  },
  { key: 'particleSize', label: 'Spark Size', section: 'Rendering', type: 'number', min: 0.06, max: 9.5, step: 0.01, default: 3.6 },
  { key: 'sparkLength', label: 'Spark Length', section: 'Rendering', description: 'Controls velocity stretch and swept trail length. Zero gives compact sparks; high values make extreme long streaks.', type: 'number', min: 0, max: 12, step: 0.01, default: 1 },
  sparkSizeVariabilityField(0.56),
  { key: 'trailFade', label: 'Trail Persistence', section: 'Rendering', description: 'Ultra-only feedback persistence for accumulated spark trails.', type: 'number', min: 0.72, max: 0.992, step: 0.004, default: 0.952, visibleRenderStyles: ['ultra'] },
  { key: 'trailContinuity', label: 'Trail Continuity', section: 'Rendering', description: 'Draws swept spark segments between frames so fast sparks read as continuous streaks instead of dotted stamps.', type: 'number', min: 0, max: 2, step: 0.01, default: 0.86, visibleRenderStyles: ['enhanced', 'ultra'] },
  { key: 'bloomStrength', label: 'Bloom Strength', section: 'Rendering', description: 'Ultra-only bloom applied during persistent trail compositing.', type: 'number', min: 0.35, max: 7.2, step: 0.05, default: 3.85, visibleRenderStyles: ['ultra'] },
  { key: 'heatRadius', label: 'Heat Radius', section: 'Rendering', type: 'number', min: 0, max: 130, step: 1, default: 72, visibleRenderStyles: ['enhanced', 'ultra'] },
  {
    key: 'rawParticleTextureSize',
    label: 'GPU Particle Capacity',
    section: 'Rendering',
    description: 'Resident GPU particle pool size. Higher values allow dense welding bursts and long-lived bounce trails.',
    type: 'select',
    default: '256',
    advanced: true,
    options: [
      { label: '128² = 16k preview', value: '128' },
      { label: '256² = 65k standard', value: '256' },
      { label: '384² = 147k dense', value: '384' },
      { label: '512² = 262k heavy', value: '512' },
      { label: '768² = 590k ultra', value: '768' },
    ],
  },
];

export const SPARKS_DEFAULTS: Record<string, unknown> = {
  emissionRate: 980,
  sparkPower: 480,
  sparkDirectionChaos: 0.42,
  torchRadius: 24,
  buildRadius: 18,
  contactHeat: 2.1,
  coreFlashRate: 3.2,
  coreFlashSize: 1,
  coreFlashVariability: 0.56,
  bounceRestitution: 0.58,
  splitChance: 0.46,
  maxSplits: 2,
  bounceBurstChance: 0.38,
  bounceBurstCount: 12,
  bounceBurstPower: 520,
  bounceBurstSpread: 1.08,
  sparkLifespan: 1,
  sparkLifespanVariability: 0.34,
  sparkTurbulence: 0.26,
  gravity: 640,
  airDrag: 0.86,
  surfaceFriction: 0.18,
  simDepth: 'layered',
  renderStyle: 'enhanced',
  particleSize: 3.6,
  sparkLength: 1,
  sparkSizeVariability: 0.56,
  trailFade: 0.952,
  trailContinuity: 0.86,
  bloomStrength: 3.85,
  heatRadius: 72,
  coreIntensity: 3.65,
  coreAfterglow: 0.38,
  rawParticleTextureSize: '256',
  style: 'white-hot',
  debug: false,
  screensaverMs: 60_000,
};
