import type { SettingsField } from '@hooksjam/pixi-lab-core';
import { sparkParticleProfileFields, type SparkParticleProfileDefinition } from '../shared/spark-rendering.js';

const SPARK_EMITTER_MODES = ['welding', 'pinwheel', 'shower'];

export const SPARK_PARTICLE_PROFILES: SparkParticleProfileDefinition[] = [
  {
    prefix: 'coreSpark',
    label: 'Core',
    description: 'White-hot source flash particles.',
    controls: ['rate', 'size', 'sizeVariability', 'lifespan', 'lifespanVariability', 'intensity', 'afterglow'],
    defaults: {
      rate: 3.2,
      size: 1,
      sizeVariability: 0.56,
      lifespan: 1,
      lifespanVariability: 0.28,
      intensity: 3.65,
      afterglow: 0.38,
    },
  },
  {
    prefix: 'primarySpark',
    label: 'Primary',
    description: 'Primary emitted sparks.',
    controls: ['size', 'length', 'lengthVariability', 'sizeVariability', 'lifespan', 'lifespanVariability', 'speedScale'],
    defaults: {
      size: 3.6,
      length: 1,
      lengthVariability: 0.38,
      sizeVariability: 0.56,
      lifespan: 1,
      lifespanVariability: 0.34,
      speedScale: 1,
    },
  },
  {
    prefix: 'bounceSpark',
    label: 'Bounce',
    description: 'Secondary sparks spawned from primary spark bounces.',
    controls: ['size', 'length', 'lengthVariability', 'sizeVariability', 'lifespan', 'lifespanVariability', 'speedScale'],
    defaults: {
      size: 0.42,
      length: 0.72,
      lengthVariability: 0.52,
      sizeVariability: 0.72,
      lifespan: 0.58,
      lifespanVariability: 0.44,
      speedScale: 0.72,
    },
  },
];

export const SPARKS_SETTINGS_FIELDS: SettingsField[] = [
  { key: 'emissionRate', label: 'Burst Rate', section: 'Input Mode', description: 'Controls how often emitter contacts emit spark bursts. Burst Density controls how many sparks are in each burst.', type: 'number', min: 0, max: 80000, step: 25, default: 980, visibleModes: SPARK_EMITTER_MODES },
  { key: 'sparkPower', label: 'Spark Power', section: 'Input Mode', type: 'number', min: 90, max: 6000, step: 25, default: 480, visibleModes: SPARK_EMITTER_MODES },
  { key: 'sparkDirectionChaos', label: 'Direction Chaos', section: 'Input Mode', description: 'Varies the initial direction of emitted sparks.', type: 'number', min: 0, max: 1, step: 0.01, default: 0.42, visibleModes: SPARK_EMITTER_MODES },
  { key: 'torchRadius', label: 'Torch Radius', section: 'Input Mode', type: 'number', min: 4, max: 56, step: 1, default: 24, visibleModes: SPARK_EMITTER_MODES },
  { key: 'buildRadius', label: 'Build Radius', section: 'Input Mode', type: 'number', min: 10, max: 44, step: 1, default: 18, visibleModes: ['build'] },
  { key: 'contactHeat', label: 'Burst Density', section: 'Input Mode', description: 'Controls sparks per burst and white-hot core intensity at the emitter contact. Burst Rate controls cadence.', type: 'number', min: 0, max: 12, step: 0.05, default: 2.1, visibleModes: SPARK_EMITTER_MODES },
  { key: 'bounceRestitution', label: 'Bounce', section: 'Physics', type: 'number', min: 0, max: 1.35, step: 0.01, default: 0.58 },
  { key: 'bounceLifeDecay', label: 'Bounce Life Decay', section: 'Physics', description: 'Removes this fraction of a spark remaining lifespan each time it bounces. Zero disables extra bounce aging; one expires on bounce.', type: 'number', min: 0, max: 1, step: 0.01, default: 0.18 },
  { key: 'bounceBurstChance', label: 'Bounce Burst Chance', section: 'Physics', description: 'Chance that a bounced spark emits a secondary burst into available GPU particle slots.', type: 'number', min: 0, max: 1, step: 0.01, default: 0.38 },
  { key: 'bounceBurstCount', label: 'Bounce Burst Count', section: 'Physics', description: 'Controls how many secondary spark slots try to respawn from each marked bounce.', type: 'number', min: 0, max: 48, step: 1, default: 12 },
  { key: 'bounceBurstCountSpeedScale', label: 'Bounce Count Speed Scale', section: 'Physics', description: 'Scales the number of secondary sparks upward as the parent spark hits faster. Zero keeps bounce burst count fixed.', type: 'number', min: 0, max: 4, step: 0.05, default: 0.8 },
  { key: 'bounceBurstImpactSpeedScale', label: 'Bounce Impact Speed Scale', section: 'Physics', description: 'Scales secondary burst launch speed upward from the parent spark impact speed. Zero keeps speed based only on the Bounce particle profile.', type: 'number', min: 0, max: 4, step: 0.05, default: 0.85 },
  { key: 'bounceBurstSpread', label: 'Bounce Burst Spread', section: 'Physics', description: 'Widens the angle of secondary sparks emitted after a bounce.', type: 'number', min: 0, max: 3, step: 0.01, default: 1.08 },
  { key: 'sparkTurbulence', label: 'Turbulence', section: 'Physics', description: 'Adds coherent in-flight directional turbulence without applying drag.', type: 'number', min: 0, max: 1, step: 0.01, default: 0.26 },
  { key: 'gravity', label: 'Gravity', section: 'Physics', type: 'number', min: 80, max: 1300, step: 10, default: 640 },
  { key: 'airDrag', label: 'Air Drag', section: 'Physics', type: 'number', min: 0, max: 4, step: 0.05, default: 0.86 },
  { key: 'surfaceFriction', label: 'Surface Friction', section: 'Physics', type: 'number', min: 0, max: 0.85, step: 0.01, default: 0.18 },
  ...SPARK_PARTICLE_PROFILES.flatMap(sparkParticleProfileFields),
  {
    key: 'simDepth',
    label: 'Simulation Depth',
    section: 'Physics',
    description: 'Optional pseudo-depth variation for spark scale and collision radius.',
    type: 'select',
    default: 'layered',
    options: [
      { label: 'Flat', value: 'flat' },
      { label: 'Layered', value: 'layered' },
      { label: 'Deep', value: 'deep' },
    ],
  },
  {
    key: 'renderStyle',
    label: 'Render Style',
    section: 'Rendering',
    type: 'select',
    default: 'enhanced',
    options: [
      { label: 'Basic', value: 'basic' },
      { label: 'Enhanced', value: 'enhanced' },
      { label: 'Ultra', value: 'ultra' },
    ],
  },
  { key: 'trailFade', label: 'Trail Persistence', section: 'Rendering', description: 'Ultra-only feedback persistence for accumulated spark trails.', type: 'number', min: 0.72, max: 0.992, step: 0.004, default: 0.952, visibleRenderStyles: ['ultra'] },
  { key: 'trailContinuity', label: 'Trail Continuity', section: 'Rendering', description: 'Draws swept spark segments between frames so fast sparks read as continuous streaks instead of dotted stamps.', type: 'number', min: 0, max: 2, step: 0.01, default: 0.86, visibleRenderStyles: ['enhanced', 'ultra'] },
  { key: 'bloomStrength', label: 'Bloom Strength', section: 'Rendering', description: 'Ultra-only bloom applied during persistent trail compositing.', type: 'number', min: 0.35, max: 7.2, step: 0.05, default: 3.85, visibleRenderStyles: ['ultra'] },
  { key: 'heatRadius', label: 'Heat Radius', section: 'Rendering', type: 'number', min: 0, max: 130, step: 1, default: 72, visibleRenderStyles: ['enhanced', 'ultra'] },
  {
    key: 'rawParticleTextureSize',
    label: 'GPU Particle Capacity',
    section: 'Rendering',
    description: 'Resident GPU particle pool size. Higher values allow dense welding bursts and long-lived bounce trails.',
    type: 'select',
    default: '256',
    advanced: true,
    options: [
      { label: '128² = 16k preview', value: '128' },
      { label: '256² = 65k standard', value: '256' },
      { label: '384² = 147k dense', value: '384' },
      { label: '512² = 262k heavy', value: '512' },
      { label: '768² = 590k ultra', value: '768' },
    ],
  },
];

export const SPARKS_DEFAULTS: Record<string, unknown> = {
  emissionRate: 980,
  sparkPower: 480,
  sparkDirectionChaos: 0.42,
  torchRadius: 24,
  buildRadius: 18,
  contactHeat: 2.1,
  bounceRestitution: 0.58,
  bounceLifeDecay: 0.18,
  bounceBurstChance: 0.38,
  bounceBurstCount: 12,
  bounceBurstCountSpeedScale: 0.8,
  bounceBurstImpactSpeedScale: 0.85,
  bounceBurstSpread: 1.08,
  sparkTurbulence: 0.26,
  gravity: 640,
  airDrag: 0.86,
  surfaceFriction: 0.18,
  simDepth: 'layered',
  renderStyle: 'enhanced',
  coreSparkRate: 3.2,
  coreSparkSize: 1,
  coreSparkSizeVariability: 0.56,
  coreSparkLifespan: 1,
  coreSparkLifespanVariability: 0.28,
  coreSparkIntensity: 3.65,
  coreSparkAfterglow: 0.38,
  primarySparkSize: 3.6,
  primarySparkLength: 1,
  primarySparkLengthVariability: 0.38,
  primarySparkSizeVariability: 0.56,
  primarySparkLifespan: 1,
  primarySparkLifespanVariability: 0.34,
  primarySparkSpeedScale: 1,
  bounceSparkSize: 0.42,
  bounceSparkLength: 0.72,
  bounceSparkLengthVariability: 0.52,
  bounceSparkSizeVariability: 0.72,
  bounceSparkLifespan: 0.58,
  bounceSparkLifespanVariability: 0.44,
  bounceSparkSpeedScale: 0.72,
  coreFlashRate: 3.2,
  coreFlashSize: 1,
  coreFlashVariability: 0.56,
  coreIntensity: 3.65,
  coreAfterglow: 0.38,
  particleSize: 3.6,
  sparkLength: 1,
  sparkSizeVariability: 0.56,
  sparkLifespan: 1,
  sparkLifespanVariability: 0.34,
  bounceBurstSpeedScale: 0.72,
  bounceBurstLifeScale: 0.58,
  trailFade: 0.952,
  trailContinuity: 0.86,
  bloomStrength: 3.85,
  heatRadius: 72,
  rawParticleTextureSize: '256',
  style: 'white-hot',
  debug: false,
  screensaverMs: 60_000,
};
