import type { SettingsField } from '@hooksjam/pixi-lab-core';

export const LAVA_LAMP_SETTINGS_FIELDS: SettingsField[] = [
  {
    key: 'renderStyle',
    label: 'Style',
    section: 'Rendering',
    type: 'select',
    options: [
      { label: 'Basic', value: 'basic' },
      { label: 'Enhanced', value: 'enhanced' },
      { label: 'Ultra', value: 'ultra' },
    ],
    default: 'ultra',
  },
  { key: 'maxParticles', label: 'Max Blobs', section: 'Physics', type: 'number', min: 64, max: 1024, step: 1, numericScale: 'powerOfTwo', default: 256 },
  { key: 'initialBlobs', label: 'Initial Blobs', section: 'Physics', type: 'number', min: 4, max: 512, step: 1, numericScale: 'powerOfTwo', default: 24 },
  { key: 'blobRadius', label: 'Blob Radius', section: 'Physics', type: 'number', min: 8, max: 54, step: 1, default: 22 },
  { key: 'gravity', label: 'Gravity', section: 'Physics', type: 'number', min: 0, max: 420, step: 5, default: 170 },
  { key: 'buoyancy', label: 'Buoyancy', section: 'Thermal Motion', type: 'number', min: 80, max: 1200, step: 10, default: 390 },
  { key: 'thermalDrive', label: 'Thermal Drive', section: 'Thermal Motion', type: 'number', min: 0, max: 5, step: 0.01, default: 1 },
  { key: 'heatRegion', label: 'Heat Region', section: 'Thermal Motion', type: 'number', min: 0.05, max: 0.75, step: 0.01, default: 0.42 },
  { key: 'coolRegion', label: 'Cool Region', section: 'Thermal Motion', type: 'number', min: 0.05, max: 0.75, step: 0.01, default: 0.46 },
  { key: 'heatRate', label: 'Heat Rate', section: 'Thermal Motion', type: 'number', min: 0, max: 2, step: 0.005, default: 0.065 },
  { key: 'coolRate', label: 'Cool Rate', section: 'Thermal Motion', type: 'number', min: 0, max: 2, step: 0.005, default: 0.095 },
  { key: 'heatTransfer', label: 'Heat Transfer', section: 'Thermal Motion', type: 'number', min: 0, max: 0.12, step: 0.001, default: 0.012 },
  { key: 'turbulence', label: 'Turbulence', section: 'Thermal Motion', type: 'number', min: 0, max: 4, step: 0.01, default: 0.55 },
  { key: 'verticalTurbulence', label: 'Vertical Turbulence', section: 'Thermal Motion', type: 'number', min: 0, max: 4, step: 0.01, default: 1 },
  { key: 'waxViscosity', label: 'Wax Viscosity', section: 'Thermal Motion', type: 'number', min: 0, max: 5, step: 0.01, default: 0.58 },
  { key: 'thermalContrast', label: 'Thermal Contrast', section: 'Rendering', type: 'number', min: 0, max: 2.5, step: 0.05, default: 1.25 },
  { key: 'enhancedQuality', label: 'Surface Detail', section: 'Enhanced Surface', type: 'number', min: 0.5, max: 2, step: 0.05, default: 1.15, visibleRenderStyles: ['enhanced', 'ultra'] },
  { key: 'liquidFieldScale', label: 'Field Resolution', section: 'Enhanced Surface', type: 'number', min: 0.45, max: 1, step: 0.01, default: 0.82, visibleRenderStyles: ['enhanced', 'ultra'] },
  { key: 'liquidParticleRadius', label: 'Surface Radius', section: 'Enhanced Surface', type: 'number', min: 0.35, max: 2.2, step: 0.01, default: 1, visibleRenderStyles: ['enhanced', 'ultra'] },
  { key: 'liquidExpansion', label: 'Expansion Factor', section: 'Enhanced Surface', type: 'number', min: 0.25, max: 2.5, step: 0.01, default: 1, visibleRenderStyles: ['enhanced', 'ultra'] },
  { key: 'liquidSplatDensity', label: 'Splat Density', section: 'Enhanced Surface', type: 'number', min: 0.35, max: 3.4, step: 0.01, default: 1.55, visibleRenderStyles: ['enhanced', 'ultra'] },
  { key: 'liquidSurfaceThreshold', label: 'Surface Threshold', section: 'Enhanced Surface', type: 'number', min: 0.04, max: 0.42, step: 0.005, default: 0.11, visibleRenderStyles: ['enhanced', 'ultra'] },
  { key: 'liquidEdgeTightness', label: 'Edge Tightness', section: 'Enhanced Surface', type: 'number', min: 0.15, max: 1, step: 0.01, default: 0.76, visibleRenderStyles: ['enhanced', 'ultra'] },
  { key: 'liquidEdgeSoftness', label: 'Edge Softness', section: 'Enhanced Surface', type: 'number', min: 0, max: 2, step: 0.01, default: 0.56, visibleRenderStyles: ['enhanced', 'ultra'] },
  { key: 'liquidRefraction', label: 'Refraction', section: 'Enhanced Surface', type: 'number', min: 0, max: 1, step: 0.01, default: 0.32, visibleRenderStyles: ['enhanced', 'ultra'] },
  { key: 'liquidGloss', label: 'Specular Gloss', section: 'Enhanced Surface', type: 'number', min: 0, max: 1, step: 0.01, default: 0.72, visibleRenderStyles: ['enhanced', 'ultra'] },
  { key: 'liquidThermalStrength', label: 'Thermal Color', section: 'Enhanced Surface', type: 'number', min: 0, max: 1, step: 0.01, default: 0.82, visibleRenderStyles: ['enhanced', 'ultra'] },
  { key: 'liquidRimLighting', label: 'Rim Lighting', section: 'Enhanced Surface', type: 'number', min: 0, max: 3, step: 0.01, default: 1.15, visibleRenderStyles: ['ultra'] },
  { key: 'liquidBloomStrength', label: 'Soft Bloom', section: 'Enhanced Surface', type: 'number', min: 0, max: 3, step: 0.01, default: 0.42, visibleRenderStyles: ['ultra'] },
  { key: 'liquidHeatShimmer', label: 'Heat Shimmer', section: 'Enhanced Surface', type: 'number', min: 0, max: 2, step: 0.01, default: 0.28, visibleRenderStyles: ['ultra'] },
  { key: 'liquidDepthDiffusion', label: 'Depth Diffusion', section: 'Enhanced Surface', type: 'number', min: 0, max: 1, step: 0.01, default: 0.22, visibleRenderStyles: ['ultra'] },
  { key: 'surfaceTension', label: 'Surface Tension', section: 'Physics', type: 'number', min: 0, max: 1, step: 0.01, default: 0.62 },
  { key: 'clumping', label: 'Clumping', section: 'Physics', type: 'number', min: 0, max: 1.5, step: 0.01, default: 0.38 },
  { key: 'inputRadius', label: 'Brush Radius', section: 'Input Mode', type: 'number', min: 24, max: 220, step: 2, default: 92, visibleModes: ['add', 'remove'] },
  { key: 'inputLift', label: 'Add Lift', section: 'Input Mode', type: 'number', min: 40, max: 720, step: 10, default: 110, visibleModes: ['add'] },
  { key: 'inputThermalRate', label: 'Add Heat', section: 'Input Mode', type: 'number', min: 0.01, max: 0.28, step: 0.005, default: 0.055, visibleModes: ['add'] },
  { key: 'metaballBlend', label: 'Metaball Blend', section: 'Rendering', type: 'number', min: 0, max: 1, step: 0.01, default: 0.86 },
  { key: 'opacity', label: 'Opacity', section: 'Rendering', type: 'number', min: 0.05, max: 1, step: 0.01, default: 0.46 },
  { key: 'substeps', label: 'Substeps', section: 'Physics', type: 'number', min: 1, max: 4, step: 1, default: 2 },
];

export const LAVA_LAMP_DEFAULTS: Record<string, unknown> = {
  renderStyle: 'ultra',
  maxParticles: 256,
  initialBlobs: 24,
  blobRadius: 22,
  gravity: 170,
  buoyancy: 390,
  thermalDrive: 1,
  heatRegion: 0.42,
  coolRegion: 0.46,
  heatRate: 0.065,
  coolRate: 0.095,
  heatTransfer: 0.012,
  turbulence: 0.55,
  verticalTurbulence: 1,
  waxViscosity: 0.58,
  thermalContrast: 1.25,
  enhancedQuality: 1.15,
  liquidFieldScale: 0.82,
  liquidParticleRadius: 1,
  liquidExpansion: 1,
  liquidSplatDensity: 1.55,
  liquidSurfaceThreshold: 0.11,
  liquidEdgeTightness: 0.76,
  liquidEdgeSoftness: 0.56,
  liquidRefraction: 0.32,
  liquidGloss: 0.72,
  liquidThermalStrength: 0.82,
  liquidRimLighting: 1.15,
  liquidBloomStrength: 0.42,
  liquidHeatShimmer: 0.28,
  liquidDepthDiffusion: 0.22,
  surfaceTension: 0.62,
  clumping: 0.38,
  inputRadius: 92,
  inputLift: 110,
  inputThermalRate: 0.055,
  metaballBlend: 0.86,
  opacity: 0.46,
  substeps: 2,
};
