import type { SettingsField } from '@hooksjam/pixi-lab-core';

export const LAVA_LAMP_SETTINGS_FIELDS: SettingsField[] = [
  {
    key: 'renderStyle',
    label: 'Style',
    section: 'Rendering',
    type: 'select',
    options: [
      { label: 'Basic', value: 'basic' },
      { label: 'Enhanced', value: 'enhanced' },
      { label: 'Ultra', value: 'ultra' },
    ],
    default: 'ultra',
  },
  { key: 'maxParticles', label: 'Max Blobs', section: 'Physics', type: 'number', min: 64, max: 1024, step: 1, numericScale: 'powerOfTwo', default: 256 },
  { key: 'initialBlobs', label: 'Initial Blobs', section: 'Physics', type: 'number', min: 16, max: 512, step: 1, numericScale: 'powerOfTwo', default: 80 },
  { key: 'blobRadius', label: 'Blob Radius', section: 'Physics', type: 'number', min: 8, max: 54, step: 1, default: 22 },
  { key: 'gravity', label: 'Gravity', section: 'Physics', type: 'number', min: 0, max: 420, step: 5, default: 170 },
  { key: 'buoyancy', label: 'Buoyancy', section: 'Thermal Motion', type: 'number', min: 80, max: 1200, step: 10, default: 390 },
  { key: 'heatRate', label: 'Heat Rate', section: 'Thermal Motion', type: 'number', min: 0, max: 0.5, step: 0.005, default: 0.065 },
  { key: 'coolRate', label: 'Cool Rate', section: 'Thermal Motion', type: 'number', min: 0, max: 0.5, step: 0.005, default: 0.095 },
  { key: 'waxViscosity', label: 'Wax Viscosity', section: 'Thermal Motion', type: 'number', min: 0, max: 1, step: 0.01, default: 0.58 },
  { key: 'thermalContrast', label: 'Thermal Contrast', section: 'Rendering', type: 'number', min: 0.35, max: 2.5, step: 0.05, default: 1.25 },
  { key: 'surfaceTension', label: 'Surface Tension', section: 'Physics', type: 'number', min: 0, max: 1, step: 0.01, default: 0.62 },
  { key: 'clumping', label: 'Clumping', section: 'Physics', type: 'number', min: 0, max: 1.5, step: 0.01, default: 0.38 },
  { key: 'inputRadius', label: 'Brush Radius', section: 'Input Mode', type: 'number', min: 24, max: 220, step: 2, default: 92, visibleModes: ['add', 'remove'] },
  { key: 'inputLift', label: 'Add Lift', section: 'Input Mode', type: 'number', min: 40, max: 720, step: 10, default: 110, visibleModes: ['add'] },
  { key: 'inputThermalRate', label: 'Add Heat', section: 'Input Mode', type: 'number', min: 0.01, max: 0.28, step: 0.005, default: 0.055, visibleModes: ['add'] },
  { key: 'metaballBlend', label: 'Metaball Blend', section: 'Rendering', type: 'number', min: 0, max: 1, step: 0.01, default: 0.86 },
  { key: 'opacity', label: 'Opacity', section: 'Rendering', type: 'number', min: 0.05, max: 1, step: 0.01, default: 0.46 },
  { key: 'substeps', label: 'Substeps', section: 'Physics', type: 'number', min: 1, max: 4, step: 1, default: 2 },
];

export const LAVA_LAMP_DEFAULTS: Record<string, unknown> = {
  renderStyle: 'ultra',
  maxParticles: 256,
  initialBlobs: 80,
  blobRadius: 22,
  gravity: 170,
  buoyancy: 390,
  heatRate: 0.065,
  coolRate: 0.095,
  waxViscosity: 0.58,
  thermalContrast: 1.25,
  surfaceTension: 0.62,
  clumping: 0.38,
  inputRadius: 92,
  inputLift: 110,
  inputThermalRate: 0.055,
  metaballBlend: 0.86,
  opacity: 0.46,
  substeps: 2,
};
