import { createEngineConfigurations, type  AmbientDefinition } from '@hooksjam/pixi-lab-core';
import { DEFAULT_AMBIENT_BEHAVIOR } from '@hooksjam/pixi-lab-core';
import { FAMILY_ORBIT_DEFAULTS } from './family-orbit.config.js';
import { FamilyOrbitScene, familyOrbitStyles } from './FamilyOrbitScene.js';

export const familyOrbitDefinition: AmbientDefinition = {
  id: 'family-orbit',
  kind: 'ambient',
  renderModes: ['fullscreen', 'background', 'widget', 'previewTile'],
  name: 'Family Orbit',
  short: 'Presence and calendar rhythms become a calm constellation of family orbits.',
  long: 'Family Orbit visualizes optional presence and calendar snapshots as deterministic member halos, closeness arcs, and activity comets. Synthetic fallback data keeps the ambient safe and demoable without family integrations, while sleep and low-motion controls make it suitable for passive dashboards.',
  tags: ['ambient', 'background', 'presence', 'calendar', 'family', 'low-motion'],
  icon: '🪐',
  paletteHint: 'living-room-constellation',
  capabilities: {
    ambient: true,
    ambientLayer: true,
    tutorial: true,
    reset: true,
    debugOverlay: true,
    styleExport: true,
    lowMotion: true,
    sleepMode: true,
    engineConfigurations: createEngineConfigurations(['basic', 'enhanced']),
    settings: true,
  },
  dataBindings: [
    { source: 'presence', optional: true, fallback: 'synthetic' },
    { source: 'calendar', optional: true, fallback: 'synthetic' },
    { source: 'time', optional: true, fallback: 'synthetic' },
    { source: 'synthetic', optional: false, fallback: 'idle' },
  ],
  behavior: {
    ...DEFAULT_AMBIENT_BEHAVIOR,
    maxBrightness: FAMILY_ORBIT_DEFAULTS.maxBrightness,
    maxParticleCount: FAMILY_ORBIT_DEFAULTS.memberCount + FAMILY_ORBIT_DEFAULTS.cometCount,
    maxUpdateHz: 30,
    allowForeground: false,
    allowBackground: true,
  },
  styles: familyOrbitStyles,
  configDefaults: { ...FAMILY_ORBIT_DEFAULTS },
  settingsFields: [
    {
      key: 'memberCount',
      label: 'Member Budget',
      description: 'Number of seeded family orbit anchors to draw.',
      type: 'number',
      min: 2,
      max: 12,
      step: 1,
      default: FAMILY_ORBIT_DEFAULTS.memberCount,
    },
    {
      key: 'cometCount',
      label: 'Activity Comets',
      description: 'Particle budget for calendar and household activity trails.',
      type: 'number',
      min: 0,
      max: 160,
      step: 4,
      default: FAMILY_ORBIT_DEFAULTS.cometCount,
    },
    {
      key: 'intensity',
      label: 'Intensity',
      description: 'Global brightness and activity multiplier for the passive constellation.',
      type: 'number',
      min: 0.08,
      max: 1,
      step: 0.04,
      default: FAMILY_ORBIT_DEFAULTS.intensity,
    },
    {
      key: 'maxBrightness',
      label: 'Max Brightness',
      description: 'Caps orbit and comet brightness for room-safe dashboards.',
      type: 'number',
      min: 0.1,
      max: 0.7,
      step: 0.04,
      default: FAMILY_ORBIT_DEFAULTS.maxBrightness,
    },
    {
      key: 'closeness',
      label: 'Closeness',
      description: 'Controls how tightly family member orbits gather near the center.',
      type: 'number',
      min: 0,
      max: 1,
      step: 0.05,
      default: FAMILY_ORBIT_DEFAULTS.closeness,
    },
    {
      key: 'activityPulse',
      label: 'Activity Pulse',
      description: 'Adjusts how strongly presence and calendar activity modulate particle size.',
      type: 'number',
      min: 0,
      max: 1,
      step: 0.05,
      default: FAMILY_ORBIT_DEFAULTS.activityPulse,
    },
    {
      key: 'orbitSpeed',
      label: 'Orbit Speed',
      description: 'Controls the member orbit and activity-comet drift speed.',
      type: 'number',
      min: 0,
      max: 1,
      step: 0.05,
      default: FAMILY_ORBIT_DEFAULTS.orbitSpeed,
    },
    {
      key: 'sleepMode',
      label: 'Sleep Mode',
      description: 'Dims and thins the constellation for overnight passive display use.',
      type: 'boolean',
      default: FAMILY_ORBIT_DEFAULTS.sleepMode,
    },
    {
      key: 'lowMotion',
      label: 'Low Motion',
      description: 'Reduces orbit speed and activity particles while preserving presence state.',
      type: 'boolean',
      default: FAMILY_ORBIT_DEFAULTS.lowMotion,
    },
  ],
  factory: () => new FamilyOrbitScene(false),
  previewFactory: () => new FamilyOrbitScene(true),
  defaultSeed: 515151,
  tutorialPages: [
    {
      icon: '👨‍👩‍👧‍👦',
      title: 'Presence without account requirements',
      body: 'Hosts can inject presence and calendar snapshots, while synthetic fallback data keeps the orbit visible in the demo without private integrations.',
    },
    {
      icon: '🪐',
      title: 'Household rhythm as orbits',
      body: 'People at home, activity, closeness, and calendar load shape member halos and small activity comets.',
    },
    {
      icon: '🌙',
      title: 'Passive display controls',
      body: 'Budgets, intensity, brightness, closeness, activity pulse, orbit speed, sleep mode, and low motion all apply while the scene is running.',
    },
  ],
};
