import type { AmbientDefinition } from '@hooksjam/pixi-lab-core';
import { DEFAULT_AMBIENT_BEHAVIOR } from '@hooksjam/pixi-lab-core';
import { TASK_GARDEN_DEFAULTS } from './task-garden.config.js';
import { TaskGardenScene, taskGardenStyles } from './TaskGardenScene.js';

export const taskGardenDefinition: AmbientDefinition = {
  id: 'task-garden',
  kind: 'ambient',
  renderModes: ['fullscreen', 'background', 'widget', 'previewTile'],
  name: 'Task Garden',
  short: 'Tasks and reminders grow into seeded plants, blooms, wilts, and completion sparkles.',
  long: 'Task Garden visualizes optional task and calendar snapshots as a deterministic living garden. New/open tasks become plants, due-soon items bloom, overdue items wilt, completed work sparkles, recurring tasks become perennial growth, and synthetic fallback data keeps the ambient demoable without organizer integrations.',
  tags: ['ambient', 'background', 'tasks', 'calendar', 'dashboard', 'low-motion'],
  icon: '🌿',
  paletteHint: 'morning-chores',
  capabilities: {
    ambient: true,
    ambientLayer: true,
    tutorial: true,
    reset: true,
    debugOverlay: true,
    styleExport: true,
    lowMotion: true,
    sleepMode: true,
    qualityModes: ['basic', 'enhanced'],
    settings: true,
  },
  dataBindings: [
    { source: 'tasks', optional: true, fallback: 'synthetic' },
    { source: 'calendar', optional: true, fallback: 'synthetic' },
    { source: 'time', optional: true, fallback: 'synthetic' },
    { source: 'synthetic', optional: false, fallback: 'idle' },
  ],
  behavior: {
    ...DEFAULT_AMBIENT_BEHAVIOR,
    maxBrightness: TASK_GARDEN_DEFAULTS.maxBrightness,
    maxParticleCount: TASK_GARDEN_DEFAULTS.plantCount + TASK_GARDEN_DEFAULTS.sparkleCount,
    maxUpdateHz: 30,
    allowForeground: false,
    allowBackground: true,
  },
  styles: taskGardenStyles,
  configDefaults: { ...TASK_GARDEN_DEFAULTS },
  settingsFields: [
    {
      key: 'plantCount',
      label: 'Plant Budget',
      description: 'Seeded plant budget for open, recurring, due, and overdue tasks.',
      type: 'number',
      min: 18,
      max: 360,
      step: 6,
      default: TASK_GARDEN_DEFAULTS.plantCount,
    },
    {
      key: 'sparkleCount',
      label: 'Completion Sparkles',
      description: 'Particle budget for completed-task fruit and sparkle events.',
      type: 'number',
      min: 0,
      max: 260,
      step: 4,
      default: TASK_GARDEN_DEFAULTS.sparkleCount,
    },
    {
      key: 'intensity',
      label: 'Intensity',
      description: 'Global brightness and activity multiplier for the passive garden.',
      type: 'number',
      min: 0.08,
      max: 1,
      step: 0.04,
      default: TASK_GARDEN_DEFAULTS.intensity,
    },
    {
      key: 'maxBrightness',
      label: 'Max Brightness',
      description: 'Caps plant and sparkle brightness for room-safe dashboards.',
      type: 'number',
      min: 0.1,
      max: 0.72,
      step: 0.04,
      default: TASK_GARDEN_DEFAULTS.maxBrightness,
    },
    {
      key: 'urgencySensitivity',
      label: 'Urgency Sensitivity',
      description: 'Controls how strongly due-soon and overdue task states change blooms and wilting.',
      type: 'number',
      min: 0,
      max: 1,
      step: 0.05,
      default: TASK_GARDEN_DEFAULTS.urgencySensitivity,
    },
    {
      key: 'growthRate',
      label: 'Growth Rate',
      description: 'Adjusts how quickly plants sway and grow from task activity.',
      type: 'number',
      min: 0,
      max: 1,
      step: 0.05,
      default: TASK_GARDEN_DEFAULTS.growthRate,
    },
    {
      key: 'completionGlow',
      label: 'Completion Glow',
      description: 'Controls completed-task fruit and sparkle visibility.',
      type: 'number',
      min: 0,
      max: 1,
      step: 0.05,
      default: TASK_GARDEN_DEFAULTS.completionGlow,
    },
    {
      key: 'sleepMode',
      label: 'Sleep Mode',
      description: 'Dims and thins the garden for overnight passive display use.',
      type: 'boolean',
      default: TASK_GARDEN_DEFAULTS.sleepMode,
    },
    {
      key: 'lowMotion',
      label: 'Low Motion',
      description: 'Reduces plant sway and sparkle movement while preserving task status.',
      type: 'boolean',
      default: TASK_GARDEN_DEFAULTS.lowMotion,
    },
  ],
  factory: () => new TaskGardenScene(false),
  previewFactory: () => new TaskGardenScene(true),
  defaultSeed: 424242,
  tutorialPages: [
    {
      icon: '🌱',
      title: 'Organizer data, safely abstracted',
      body: 'Hosts can inject task and calendar snapshots, while synthetic fallback data keeps the garden visible in the demo without account access.',
    },
    {
      icon: '🌼',
      title: 'Task states become plants',
      body: 'Open tasks grow leaves, due-soon items bloom, overdue work wilts, completed items sparkle, and recurring tasks become perennial growth.',
    },
    {
      icon: '🌙',
      title: 'Passive display controls',
      body: 'Budgets, intensity, brightness, urgency, growth, completion glow, sleep mode, and low motion all apply while the scene is running.',
    },
  ],
};
