import { createEngineConfigurations, type  AmbientDefinition } from '@hooksjam/pixi-lab-core';
import { DEFAULT_AMBIENT_BEHAVIOR } from '@hooksjam/pixi-lab-core';
import { MEMORY_DRIFT_DEFAULTS } from './memory-drift.config.js';
import { MemoryDriftScene, memoryDriftStyles } from './MemoryDriftScene.js';

export const memoryDriftDefinition: AmbientDefinition = {
  id: 'memory-drift',
  kind: 'ambient',
  renderModes: ['fullscreen', 'background', 'widget', 'previewTile'],
  name: 'Memory Drift',
  short: 'Photo-palette memories drift as a calm, synthetic-safe family background.',
  long: 'Memory Drift turns optional photo palette metadata into seeded floating memory frames and dust motes. It remains fully demoable with synthetic fallback data, supports passive dashboard modes, and exposes live controls for budget, brightness, warmth, nostalgia, sleep, and low motion.',
  tags: ['ambient', 'background', 'photos', 'memory', 'family', 'low-motion'],
  icon: '🖼️',
  paletteHint: 'shoebox-glow',
  capabilities: {
    ambient: true,
    ambientLayer: true,
    tutorial: true,
    reset: true,
    debugOverlay: true,
    styleExport: true,
    lowMotion: true,
    sleepMode: true,
    engineConfigurations: createEngineConfigurations(['basic', 'enhanced']),
    settings: true,
  },
  dataBindings: [
    { source: 'photos', optional: true, fallback: 'synthetic' },
    { source: 'media', optional: true, fallback: 'synthetic' },
    { source: 'time', optional: true, fallback: 'synthetic' },
    { source: 'synthetic', optional: false, fallback: 'idle' },
  ],
  behavior: {
    ...DEFAULT_AMBIENT_BEHAVIOR,
    maxBrightness: MEMORY_DRIFT_DEFAULTS.maxBrightness,
    maxParticleCount: MEMORY_DRIFT_DEFAULTS.memoryCount + MEMORY_DRIFT_DEFAULTS.moteCount,
    maxUpdateHz: 30,
    allowForeground: false,
    allowBackground: true,
  },
  styles: memoryDriftStyles,
  configDefaults: { ...MEMORY_DRIFT_DEFAULTS },
  settingsFields: [
    {
      key: 'memoryCount',
      label: 'Memory Frames',
      description: 'Number of seeded photo-memory anchors to draw.',
      type: 'number',
      min: 8,
      max: 72,
      step: 2,
      default: MEMORY_DRIFT_DEFAULTS.memoryCount,
    },
    {
      key: 'moteCount',
      label: 'Dust Motes',
      description: 'Particle budget for small palette motes drifting between memories.',
      type: 'number',
      min: 0,
      max: 220,
      step: 4,
      default: MEMORY_DRIFT_DEFAULTS.moteCount,
    },
    {
      key: 'intensity',
      label: 'Intensity',
      description: 'Global activity and glow multiplier for the passive memory field.',
      type: 'number',
      min: 0.08,
      max: 1,
      step: 0.04,
      default: MEMORY_DRIFT_DEFAULTS.intensity,
    },
    {
      key: 'maxBrightness',
      label: 'Max Brightness',
      description: 'Caps the photo glow for room-safe always-on displays.',
      type: 'number',
      min: 0.1,
      max: 0.7,
      step: 0.04,
      default: MEMORY_DRIFT_DEFAULTS.maxBrightness,
    },
    {
      key: 'paletteWarmth',
      label: 'Palette Warmth',
      description: 'Warms or cools the generated photo palette when no real photo metadata is connected.',
      type: 'number',
      min: 0,
      max: 1,
      step: 0.05,
      default: MEMORY_DRIFT_DEFAULTS.paletteWarmth,
    },
    {
      key: 'driftSpeed',
      label: 'Drift Speed',
      description: 'Controls memory-frame and mote movement speed.',
      type: 'number',
      min: 0,
      max: 1,
      step: 0.05,
      default: MEMORY_DRIFT_DEFAULTS.driftSpeed,
    },
    {
      key: 'nostalgia',
      label: 'Nostalgia',
      description: 'Pulls memory frames into slower, warmer, older-photo motion.',
      type: 'number',
      min: 0,
      max: 1,
      step: 0.05,
      default: MEMORY_DRIFT_DEFAULTS.nostalgia,
    },
    {
      key: 'sleepMode',
      label: 'Sleep Mode',
      description: 'Dims and thins the memory field for overnight display use.',
      type: 'boolean',
      default: MEMORY_DRIFT_DEFAULTS.sleepMode,
    },
    {
      key: 'lowMotion',
      label: 'Low Motion',
      description: 'Reduces drift and mote density while preserving photo-palette state.',
      type: 'boolean',
      default: MEMORY_DRIFT_DEFAULTS.lowMotion,
    },
  ],
  factory: () => new MemoryDriftScene(false),
  previewFactory: () => new MemoryDriftScene(true),
  defaultSeed: 616161,
  tutorialPages: [
    {
      icon: '🖼️',
      title: 'Private by default',
      body: 'Hosts can inject photo palette summaries, but the demo uses synthetic fallback data so no personal photo integration is required.',
    },
    {
      icon: '✨',
      title: 'Photo palettes as motion',
      body: 'Palette warmth, colorfulness, and memory count shape the glow, frame sizes, and drifting dust motes.',
    },
    {
      icon: '🌙',
      title: 'Passive display controls',
      body: 'Budgets, intensity, brightness, warmth, nostalgia, drift speed, sleep mode, and low motion apply while the scene is running.',
    },
  ],
};
