import type { SettingsField } from '@hooksjam/pixi-lab-core';

export const PARTICLE_FLUID_SETTINGS_FIELDS: SettingsField[] = [
  {
    key: 'renderStyle',
    label: 'Style',
    section: 'Rendering',
    type: 'select',
    options: [
      { label: 'Dye Cloud', value: 'dye' },
      { label: 'Plasma Sheet', value: 'plasma' },
      { label: 'Droplets', value: 'droplets' },
    ],
    default: 'dye',
  },
  {
    key: 'maxParticles',
    label: 'Particle Budget',
    section: 'Simulation',
    description: 'Maximum live particle count. Higher powers of two produce denser fluid but cost more CPU simulation and GPU upload work.',
    type: 'number',
    min: 1024,
    max: 1048576,
    step: 1,
    numericScale: 'powerOfTwo',
    default: 262144,
  },
  { key: 'particleRadius', label: 'Point Size', section: 'Rendering', type: 'number', min: 0.75, max: 4, step: 0.05, default: 1.25 },
  { key: 'fieldCellSize', label: 'Flow Cell Size', section: 'Simulation', type: 'number', min: 4, max: 18, step: 1, default: 7 },
  { key: 'solverIterations', label: 'Pressure Iterations', section: 'Simulation', type: 'number', min: 4, max: 36, step: 1, default: 18 },
  { key: 'fluidTightness', label: 'Flow Coupling', section: 'Simulation', type: 'number', min: 0.15, max: 1.35, step: 0.01, default: 1 },
  { key: 'viscosity', label: 'Diffusion', section: 'Simulation', type: 'number', min: 0.01, max: 0.72, step: 0.01, default: 0.12 },
  { key: 'vorticity', label: 'Vorticity', section: 'Simulation', type: 'number', min: 0, max: 3.4, step: 0.05, default: 0.48 },
  { key: 'drag', label: 'Field Drag', section: 'Simulation', type: 'number', min: 0.01, max: 0.32, step: 0.005, default: 0.025 },
  { key: 'substeps', label: 'Substeps', section: 'Simulation', type: 'number', min: 1, max: 4, step: 1, default: 1 },
  { key: 'metaballBlend', label: 'Dye Field', section: 'Rendering', type: 'number', min: 0, max: 1, step: 0.01, default: 0.86 },
  { key: 'opacity', label: 'Particle Opacity', section: 'Rendering', type: 'number', min: 0.06, max: 1, step: 0.01, default: 0.92 },
  { key: 'inputRadius', label: 'Input Radius', section: 'Input Mode', type: 'number', min: 20, max: 190, step: 2, default: 74, visibleModes: ['vortex', 'inject', 'repel'] },
  { key: 'inputForce', label: 'Input Force', section: 'Input Mode', type: 'number', min: 2, max: 52, step: 1, default: 18, visibleModes: ['vortex', 'inject', 'repel'] },
  { key: 'injectRate', label: 'Inject Rate', section: 'Input Mode', type: 'number', min: 20, max: 920, step: 20, default: 260, visibleModes: ['inject'] },
  { key: 'dyeSpread', label: 'Dye Spread', section: 'Input Mode', type: 'number', min: 0.02, max: 0.42, step: 0.01, default: 0.16, visibleModes: ['inject', 'vortex'] },
];

export const PARTICLE_FLUID_DEFAULTS: Record<string, unknown> = {
  renderStyle: 'dye',
  maxParticles: 262144,
  particleRadius: 1.25,
  fieldCellSize: 7,
  solverIterations: 18,
  fluidTightness: 1,
  viscosity: 0.12,
  vorticity: 0.48,
  drag: 0.025,
  substeps: 1,
  metaballBlend: 0.86,
  opacity: 0.92,
  inputRadius: 74,
  inputForce: 18,
  injectRate: 260,
  dyeSpread: 0.16,
};
