import type { EffectDefinition } from '@hooksjam/pixi-lab-core';
import { LEAVES_POLLEN_DEFAULTS } from './leaves-pollen.config.js';
import { LeavesPollenScene, leavesPollenStyleManifest } from './LeavesPollenScene.js';

export const leavesPollenDefinition: EffectDefinition = {
  id: 'leaves-pollen',
  kind: 'effect',
  renderModes: ['foregroundOverlay', 'fullscreen', 'previewTile'],
  name: 'Leaves/Pollen',
  short: 'A seasonal foreground overlay of drifting leaves and pollen motes with synthetic fallback data.',
  long: 'Leaves/Pollen is a foreground-safe seasonal overlay for dashboards and gallery demos. It renders deterministic seeded particles, reads optional weather/time snapshots for wind, pollen, and seasonal phase, and falls back to synthetic data when live integrations are unavailable.',
  tags: ['effect', 'overlay', 'seasonal', 'pollen', 'leaves', 'low-motion'],
  icon: '🍂',
  paletteHint: 'autumn-window',
  capabilities: {
    reset: true,
    debugOverlay: true,
    styleExport: true,
    lowMotion: true,
    sleepMode: true,
    qualityModes: ['basic', 'enhanced'],
    settings: true,
  },
  configDefaults: { ...LEAVES_POLLEN_DEFAULTS },
  styleManifest: leavesPollenStyleManifest,
  settingsFields: [
    {
      key: 'particleCount',
      label: 'Particle Count',
      description: 'Seeded leaf and pollen particle budget for the foreground overlay.',
      type: 'number',
      min: 48,
      max: 1200,
      step: 24,
      default: LEAVES_POLLEN_DEFAULTS.particleCount,
    },
    {
      key: 'intensity',
      label: 'Intensity',
      description: 'Global brightness and motion multiplier for the seasonal drift.',
      type: 'number',
      min: 0.08,
      max: 1,
      step: 0.04,
      default: LEAVES_POLLEN_DEFAULTS.intensity,
    },
    {
      key: 'maxBrightness',
      label: 'Max Brightness',
      description: 'Caps particle alpha so the overlay does not obscure UI.',
      type: 'number',
      min: 0.1,
      max: 0.78,
      step: 0.04,
      default: LEAVES_POLLEN_DEFAULTS.maxBrightness,
    },
    {
      key: 'breeze',
      label: 'Breeze',
      description: 'Manual horizontal drift mixed with weather or synthetic fallback wind.',
      type: 'number',
      min: 0,
      max: 1,
      step: 0.04,
      default: LEAVES_POLLEN_DEFAULTS.breeze,
    },
    {
      key: 'driftSpeed',
      label: 'Drift Speed',
      description: 'Controls leaf fall and pollen float speed while preserving deterministic paths.',
      type: 'number',
      min: 0,
      max: 1,
      step: 0.04,
      default: LEAVES_POLLEN_DEFAULTS.driftSpeed,
    },
    {
      key: 'pollenMix',
      label: 'Pollen Mix',
      description: 'Balances bright pollen motes against larger drifting leaves.',
      type: 'number',
      min: 0,
      max: 1,
      step: 0.04,
      default: LEAVES_POLLEN_DEFAULTS.pollenMix,
    },
    {
      key: 'sleepMode',
      label: 'Sleep Mode',
      description: 'Dims and thins seasonal drift for overnight passive displays.',
      type: 'boolean',
      default: LEAVES_POLLEN_DEFAULTS.sleepMode,
    },
    {
      key: 'lowMotion',
      label: 'Low Motion',
      description: 'Reduces visible particles and motion while keeping the overlay legible.',
      type: 'boolean',
      default: LEAVES_POLLEN_DEFAULTS.lowMotion,
    },
  ],
  factory: () => new LeavesPollenScene(false),
  previewFactory: () => new LeavesPollenScene(true),
  defaultSeed: 20260529,
  tutorialPages: [
    {
      icon: '🍂',
      title: 'Seasonal foreground drift',
      body: 'The effect renders transparent leaves and pollen with capped brightness so dashboard UI remains readable.',
    },
    {
      icon: '🌿',
      title: 'Weather optional',
      body: 'Wind, pollen, and seasonal phase can come from weather/time snapshots, but synthetic fallback data keeps the gallery demoable without integrations.',
    },
    {
      icon: '🌙',
      title: 'Passive controls',
      body: 'Particle budget, intensity, brightness, breeze, drift speed, pollen mix, sleep mode, and low motion all apply while the scene runs.',
    },
  ],
};
